### ISSUE TITLE
Undocumented method: ydk.path.SchemaNode.get_keys()

### ISSUE THREAD

**Issue by tdesh10** [CiscoDevNet/ydk-gen#1012]
The `ydk.path.SchemaNode` object has a method `get_keys()`, but this method is not defined in the [YDK Path API Documentation](http://ydk.cisco.com/py/docs/api/path/path.html).

**Comment by ygorelik** [comment]
Resolved in YDK-0.8.5.

**Comment by ygorelik** [comment]
Tested the docs for 0.8.6.5 and confirm that the issue has been fixed. Hence closing the issue.
