### ISSUE TITLE
ydk.path.DataNode.get_value() is listed as .get() in the documentation

### ISSUE THREAD

**Issue by tdesh10** [CiscoDevNet/ydk-gen#1013]
In the Path API documentation, the method[`ydk.path.DataNode.get()`](http://ydk.cisco.com/py/docs/api/path/data_node.html#ydk.path.DataNode.get) is listed. However, this method does not exist in the Path API. The method that returns a datanode's value is called `get_value()`.

**Comment by ygorelik** [comment]
Resolved in YDK-0.8.5.

**Comment by ygorelik** [comment]
Tested the docs for 0.8.6.5 and confirm that the issue has been fixed. Hence closing the issue.
