### ISSUE TITLE
YDK-py: Segmentation fault on simple crud.read of IOS XE

### ISSUE THREAD

**Issue by uavsec** [CiscoDevNet/ydk-gen#1015]
Hi.

## Expected Behavior

root@5a471cf8bc4a:~/ydk-py# ./test.py
ydk.models.cisco_ios_xe.Cisco_IOS_XE_native.Native

## Current Behavior

root@5a471cf8bc4a:~/ydk-py# ./test.py 
Segmentation fault (core dumped)

## Steps to Reproduce

Run the script towards a c9500 with IOS XE 16.12

## Your Script

```
#!/usr/bin/env python3

import sys
import logging

from ydk.services import CRUDService
from ydk.providers import NetconfServiceProvider
# from ydk.models.openconfig import openconfig_interfaces as open_interfaces
from ydk.models.cisco_ios_xe import Cisco_IOS_XE_native as xe_native

def read(provider):
    crud = CRUDService()

    native = xe_native.Native()

    config = crud.read(provider, native)

    print(config)

if __name__ == '__main__':
    provider = NetconfServiceProvider(address='xxxxxxx', port=830, username='netconf', password='netconf', protocol='ssh')

    read(provider)
```

## Logs

[script_log.txt](https://github.com/CiscoDevNet/ydk-gen/files/4924085/script_log.txt)

## System Information
Docker container:  ydkdev/ydk-py  
- only thing done on it is apt update, apt upgrade and apt install vim
- same issue happens when I installed YDK on another ubuntu 18.04 system as well

**Comment by uavsec** [comment]
Same thing works ok if I run it towards a CSR.

**Comment by ygorelik** [comment]
Not a YDK issue. This is Netconf issue on c9500 with IOS XE 16.12.

**Comment by 111pontes** [comment]
Even if router is at fault, YDK shouldn't segfault.

**Comment by uavsec** [comment]
Hey.
Updated the box to 17.2 IOS XE and the issue is still there. The only thing I can think of now is that 19GB RAM on the VM I'm running this script is not enough.
[segfault_17.2xe.txt](https://github.com/CiscoDevNet/ydk-gen/files/4936265/segfault_17.2xe.txt)
