### ISSUE TITLE
openconfig bundle bgp neigbors apply-policy field is str instead of List[str]

### ISSUE THREAD

**Issue by rinhomdf** [CiscoDevNet/ydk-gen#1027]
Openconfig bundle coming with 0.8.5 (0.1.8) has a type mismatch according to what is reported in the generated docs.

> import_policy
> list of policy names in sequence to be applied on receiving a routing update in the current context, e.g., for the current peer group, neighbor, address family, etc
> 
> type: list of str

## Expected Behavior
The following apply_policy defintion should not return YModel error of incorrect type

```
bgp_neighbors: openconfig_bgp.Bgp.Neighbors
neighbor = bgp_neighbors.Neighbor()
...
neighbor.apply_policy.config.import_policy = ["policy1", "policy2"]
```

## Current Behavior
Instead it returns a YModel Error exception when passing values
```
bgp_neighbors: openconfig_bgp.Bgp.Neighbors
neighbor = bgp_neighbors.Neighbor()
...
neighbor.apply_policy.config.import_policy = ["policy1", "policy2"]
```
ydk.errors.YModelError: Invalid value ['policy1', 'policy2'] for 'import_policy'. Got type: 'list'. Expected types: 'str'

It has to be replaced for now with:
```
neighbor.apply_policy.config.import_policy = "policy1"
```

## System Information
python 3.7.7
ydk 0.8.5
ydk-models-openconfig 0.1.8

**Comment by ygorelik** [comment]
This is not a bug, but a request of new feature, YDK API enhancement.

The _neighbor.apply_policy.config.import_policy_ is _YLeafList_ object, therefore multiple value assignment could be done this way:
```
neighbor.apply_policy.config.import_policy.extend(["policy1", "policy2"])
```
or
```
neighbor.apply_policy.config.import_policy = "policy1"
neighbor.apply_policy.config.import_policy = "policy2"
```
