### ISSUE TITLE
Upgrade generator dependencies and provide argument to ignore selected errors

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#1030]
SDK generator relies on a rather old version (1.6) of `pyang` for model validation.  There are valid YANG models that that version can't validate and therefore, the generator is unable to process the models successfully.  The generator dependencies should be updated and access to `--ignore-error` argument in `pyang` should be provided, so generation can proceed for errors that can be safely ignored.

**Comment by ygorelik** [comment]
Addressed the issue in YDK-0.8.6 with switching to pyang version 2.5.
