### ISSUE TITLE
sudo-ing wget in install script doesn't respect http proxy environment settings

### ISSUE THREAD

**Issue by valeriodigregorio** [CiscoDevNet/ydk-gen#1038]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
WGET during installation shouldn't fail

## Current Behavior
WGET during installation fails when done in a sudo command if the current user has environment settings for http proxy.

## Steps to Reproduce
Setup http_proxy env var in your shell then run the install_ydk.sh

## Your Script
No script available.

## Logs
I can't repro the issue right now to collect logs. I will do it upon request if needed.

## System Information
Ubuntu bionic on docker container.

**Comment by ygorelik** [comment]
None of the YDK scripts uses _http_proxy_ as environment variable. There for the described symptoms could not be considered as YDK defect. I suggest to close this issue and move the discussion to [Cisco Community](https://community.cisco.com/t5/yang-development-kit-ydk/bd-p/5475j-disc-dev-net-ydk).
