### ISSUE TITLE
v0.8.5 not released

### ISSUE THREAD

**Issue by fdomain** [CiscoDevNet/ydk-gen#1052]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

When trying to build from source (following https://github.com/CiscoDevNet/ydk-gen#build-from-source), the documentation refers to the version 0.8.5, however this tag is not available on the repository.

## Expected Behavior
The tag v0.8.5 is available on git repo

## Current Behavior
The latest version released is v0.8.4

## Steps to Reproduce

```
git clone https://github.com/CiscoDevNet/ydk-gen.git -b 0.8.5
Cloning into 'ydk-gen'...
fatal: Remote branch 0.8.5 not found in upstream origin
```

**Comment by ygorelik** [comment]
The releases 0.8.5 and 0.8.5.2 currently available only in my private [fork](https://github.com/ygorelik/ydk-gen). To download YDK please use commands:
```
git clone https://github.com/ygorelik/ydk-gen.git -b 0.8.5
or
git clone https://github.com/ygorelik/ydk-gen.git -b 0.8.5.2
``` 
The latest documentation is available [here](https://ygorelik.github.io/ydk-gen/).

This is not the YDK issue and further discussions on this subject must be moved to [Cisco Community](https://community.cisco.com/t5/yang-tools/bd-p/5475j-disc-dev-net-ydk) website.

**Comment by ygorelik** [comment]
Added tag 0.8.5 and release notes.
