### ISSUE TITLE
API Documentation not available on http://ydk.cisco.com/py/docs

### ISSUE THREAD

**Issue by vaniatoperich** [CiscoDevNet/ydk-gen#1063]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

**Comment by ygorelik** [comment]
Online documentation is available on [GitHub Pages](https://ygorelik.github.io/ydk-gen/). The same documentation can be viewed locally from the ydk-gen repository, example:
```
cd ydk-gen
firefox docs/index.html &
```
