### ISSUE TITLE
Document issue, YDKGEN_HOME=`pwd` and PYTHON_VENV=$HOME/ydk_vne are seen as optional

### ISSUE THREAD

**Issue by jayapr** [CiscoDevNet/ydk-gen#1065]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior

export YDKGEN_HOME=`pwd`  # optional
export PYTHON_VENV=$HOME/ydk_vne  # optional

These should be mandatory

## Current Behavior
Currently these are optional

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

**Comment by ygorelik** [comment]
Setting of these environment variables could be omitted if default locations are used.
