### ISSUE TITLE
YDK C++ core library install fails on CentOS 8 stream

### ISSUE THREAD

**Issue by fisher-m** [CiscoDevNet/ydk-gen#1076]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
Expect that the YDK C++ core library installs successfully with the commands listed in the Steps to Reproduce Section below.

## Current Behavior
`[fisher_m@localhost ydk-gen-master]$ export YDKGEN_HOME=`pwd`
[fisher_m@localhost ydk-gen-master]$ export PYTHON_VENV=$HOME/ydk_vne
[fisher_m@localhost ydk-gen-master]$ ./install_ydk.sh --cpp --core --venv
YDK-0.8.6.3 installation options:
 - create Python virtual environment = yes
 - programming language = cpp
 - install dependencies = yes
 - install core package = yes
 - install service package = no
*** Wed Jan 11 10:34:33 MST 2023 *** install_ydk.sh | Running OS type: Linux 
*** Wed Jan 11 10:34:33 MST 2023 *** install_ydk.sh | OS info: CentOS Stream release 8
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
CentOS Stream release 8
CentOS Stream release 8 
*** Wed Jan 11 10:34:33 MST 2023 *** install_ydk.sh | LD_LIBRARY_PATH is set to: :/usr/local/lib:/usr/local/lib64:/usr/lib64 
*** Wed Jan 11 10:34:33 MST 2023 *** install_ydk.sh | Running: /home/fisher_m/YangDevKit/YDK-0.8.6/CiscoDevNet/ydk-gen-master/test/dependencies_centos.sh 
*** Wed Jan 11 10:34:33 MST 2023 *** dependencies_centos.sh | Installing dependencies 
*** Wed Jan 11 10:34:33 MST 2023 *** dependencies_centos.sh | Running Centos/RHEL version 8 
[sudo] password for fisher_m: 
Sorry, try again.
[sudo] password for fisher_m: 
Last metadata expiration check: 0:40:41 ago on Wed 11 Jan 2023 09:54:39 AM MST.
Package dnf-plugins-core-4.0.21-17.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
CentOS Stream 8 - PowerTools                                                                 7.8 kB/s | 4.4 kB     00:00    
Last metadata expiration check: 0:00:01 ago on Wed 11 Jan 2023 09:54:39 AM MST.
Package doxygen-1:1.8.14-12.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 0:00:03 ago on Wed 11 Jan 2023 10:35:23 AM MST.
Package lcov-1.14-6.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
/usr/bin/gcc
*** Wed Jan 11 10:35:28 MST 2023 *** dependencies_centos.sh | Current gcc/g++ version is 8.5.0 
*** Wed Jan 11 10:35:28 MST 2023 *** dependencies_centos.sh | Current Go version is 1.13.1 
/home/fisher_m/.local/share/containers/storage/overlay/347cc11a60b0f4b48f677f63e6f6146664e2a21ddeffbaf4f07b486ff7becda3/diff/usr/lib/x86_64-linux-gnu/libssh_threads.so
/home/fisher_m/.local/share/containers/storage/overlay/347cc11a60b0f4b48f677f63e6f6146664e2a21ddeffbaf4f07b486ff7becda3/diff/usr/lib/x86_64-linux-gnu/libssh_threads.so.4
/home/fisher_m/.local/share/containers/storage/overlay/347cc11a60b0f4b48f677f63e6f6146664e2a21ddeffbaf4f07b486ff7becda3/diff/usr/lib/x86_64-linux-gnu/libssh_threads.so.4.5.0
/home/fisher_m/.local/share/containers/storage/overlay/3519ec1d02ab0e3b1af0f9019d9b80a76c0f32de087f6063c45f0aacd5f5214f/diff/usr/lib/x86_64-linux-gnu/libssh_threads.so
/home/fisher_m/.local/share/containers/storage/overlay/3519ec1d02ab0e3b1af0f9019d9b80a76c0f32de087f6063c45f0aacd5f5214f/diff/usr/lib/x86_64-linux-gnu/libssh_threads.so.4
/home/fisher_m/.local/share/containers/storage/overlay/3519ec1d02ab0e3b1af0f9019d9b80a76c0f32de087f6063c45f0aacd5f5214f/diff/usr/lib/x86_64-linux-gnu/libssh_threads.so.4.5.0
/home/fisher_m/.local/share/containers/storage/overlay/44b3251bac8c83f4cf7de4d40c42078131ba8956a4ea0efaf1818abd79360f86/diff/usr/lib/x86_64-linux-gnu/libssh_threads.so
/home/fisher_m/.local/share/containers/storage/overlay/44b3251bac8c83f4cf7de4d40c42078131ba8956a4ea0efaf1818abd79360f86/diff/usr/lib/x86_64-linux-gnu/libssh_threads.so.4
/home/fisher_m/.local/share/containers/storage/overlay/44b3251bac8c83f4cf7de4d40c42078131ba8956a4ea0efaf1818abd79360f86/diff/usr/lib/x86_64-linux-gnu/libssh_threads.so.4.5.0
/home/fisher_m/.local/share/containers/storage/overlay/641fa9704fffde63e3ee4669e59fb75af5a4892f6ab90cb5dce3ab682e31df0e/diff/root/ydk-gen/3d_party/linux/ubuntu/lib/libssh_threads.so.4.5.0
/home/fisher_m/.local/share/containers/storage/overlay/77849bbcd1753ec436cf959250ddc037b8b5eb036c5db769b5a0e334d70a5cb2/diff/root/ydk-gen/3d_party/linux/ubuntu/lib/libssh_threads.so.4.5.0
/home/fisher_m/.local/share/containers/storage/overlay/9640cf790d960daaa85c19fdc8cb2cfaf4a82977a7634ce756b230b5dfd63f11/diff/usr/lib/x86_64-linux-gnu/libssh_threads.so
/home/fisher_m/.local/share/containers/storage/overlay/9640cf790d960daaa85c19fdc8cb2cfaf4a82977a7634ce756b230b5dfd63f11/diff/usr/lib/x86_64-linux-gnu/libssh_threads.so.4
/home/fisher_m/.local/share/containers/storage/overlay/9640cf790d960daaa85c19fdc8cb2cfaf4a82977a7634ce756b230b5dfd63f11/diff/usr/lib/x86_64-linux-gnu/libssh_threads.so.4.5.0
/home/fisher_m/.local/share/containers/storage/overlay/aafa2b53d1cab9222fd8b666c029bd9952a76bc0039a2a239a49c57325932ec6/diff/root/ydk-gen/3d_party/linux/ubuntu/lib/libssh_threads.so.4.5.0
/home/fisher_m/.local/share/containers/storage/overlay/f8ffaf1757611cc3408a8d0f73b673a595e16e69d9a534b5851fe948878b6436/diff/root/ydk-gen/3d_party/linux/ubuntu/lib/libssh_threads.so.4.5.0
/home/fisher_m/YangDevKit/YDK-0.8.6/CiscoDevNet/old/ydk-gen-master/3d_party/linux/ubuntu/lib/libssh_threads.so.4.5.0
/home/fisher_m/YangDevKit/YDK-0.8.6/CiscoDevNet/ydk-gen-master/3d_party/linux/ubuntu/lib/libssh_threads.so.4.5.0
/home/fisher_m/YangDevKit/YDK-0.8.6/ygorelik/ydk-gen/3d_party/linux/ubuntu/lib/libssh_threads.so.4.5.0
/usr/lib64/libssh_threads.so
/usr/lib64/libssh_threads.so.4
/usr/lib64/libssh_threads.so.4.8.7
/home/fisher_m/YangDevKit/YDK-0.8.6/CiscoDevNet/ydk-gen-master
*** Wed Jan 11 10:35:30 MST 2023 *** install_ydk.sh | Running: source /home/fisher_m/ydk_vne/bin/activate 
*** Wed Jan 11 10:35:30 MST 2023 *** install_ydk.sh | Checking python3 version and installation 
Python 3.6.8
*** Wed Jan 11 10:35:30 MST 2023 *** install_ydk.sh | Checking pip3 version and installation 
pip 9.0.3 from /home/fisher_m/ydk_vne/lib64/python3.6/site-packages (python 3.6)
*** Wed Jan 11 10:35:31 MST 2023 *** install_ydk.sh | Initializing Python requirements 
Collecting pyang==2.5 (from -r requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7fa23cd91d30>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /artifactory/api/pypi/pypi-virtual/simple/pyang/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7fa23cd914a8>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /artifactory/api/pypi/pypi-virtual/simple/pyang/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7fa23cd91898>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /artifactory/api/pypi/pypi-virtual/simple/pyang/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7fa23cd91160>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /artifactory/api/pypi/pypi-virtual/simple/pyang/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7fa23cd6b9b0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /artifactory/api/pypi/pypi-virtual/simple/pyang/
  Could not find a version that satisfies the requirement pyang==2.5 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for pyang==2.5 (from -r requirements.txt (line 1))
You are using pip version 9.0.3, however version 22.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
*** Wed Jan 11 10:35:39 MST 2023 *** install_ydk.sh | Writing .env file 
*** Wed Jan 11 10:35:39 MST 2023 *** install_ydk.sh | Installing C++ core library 
*** Wed Jan 11 10:35:39 MST 2023 *** install_ydk.sh | Running: python3 generate.py --core --cpp -is 
Traceback (most recent call last):
  File "generate.py", line 32, in <module>
    from git import Repo
ModuleNotFoundError: No module named 'git'
*** Wed Jan 11 10:35:39 MST 2023 *** install_ydk.sh | Exiting 'python3 generate.py --core --cpp -is' with status=1 
[fisher_m@localhost ydk-gen-master]$ 
`

## Steps to Reproduce
cd ~/ydk-gen-master
export YDKGEN_HOME=`pwd`
export PYTHON_VENV=$HOME/ydk_vne
./install_ydk.sh --cpp --core --venv

## System Information
Architecture = X86_64, VMWare Workstation VM
OS = CentOS 8 stream
g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-17)
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-17)
Python 3.6.8
git version 2.31.1
pyang 2.5.3

**Comment by ygorelik** [comment]
This is not YDK software issue, but rather issue with the server communication with pypi.org. Check that you can reliably install python packages from that site and then repeat the installation steps.

**Comment by fisher-m** [comment]
Thanks for the feedback.  I was able to get the YDK C++ core library to build after updating the URL in my pip.conf.  Thanks again.
