### ISSUE TITLE
ydk 0.5.5 - Secondary mechanism failed more than one identity with name <identity-name> found

### ISSUE THREAD

**Issue by janarbe** [CiscoDevNet/ydk-gen#1084]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
~/ydk/providers/_decoder.py file need to handle if the same Identity element exist in two or more different yang files.

## Current Behavior
~/ydk/providers/_decoder.py file is giving error message if an Identity element exist in two yang file.

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

**Comment by ygorelik** [comment]
This is not supported YDK version and therefore will not be fixed.
