### ISSUE TITLE
How to write a netconf server

### ISSUE THREAD

**Issue by knightswim** [CiscoDevNet/ydk-gen#1085]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
How to write a netconf server with ydk?

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

**Comment by ygorelik** [comment]
Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.
