### ISSUE TITLE
ydk.io and ciscodevnet.github.io/ydk-py/ not working correctly

### ISSUE THREAD

**Issue by hyberdk** [CiscoDevNet/ydk-gen#1088]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
ydk.io for I was expected to be able to browse http://ydk.io as referenced in the project.

for ciscodevnet.github.io/ydk-py/ i was expecting more than a "bare" html site.

## Current Behavior
idk.io seems to have a DNS issue

ciscodevnet.github.io/ydk-py/ are missing a lot of css and java scripts
![image](https://github.com/CiscoDevNet/ydk-gen/assets/3530739/c6f5e9ec-1d64-4955-8a53-7767ff288a9f)

## Steps to Reproduce
browse any of the websites.

## Your Script

N/A

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

N/A

## System Information
Chrome broweser ;-)

**Comment by ygorelik** [comment]
The [GitHub pages](http://ciscodevnet.github.io/ydk-gen/) are working just fine, but for some reason they do not pickup the CSS pages, hence the visible picture is somewhat simplified. The ydk-py is not supported anymore.

**Comment by ygorelik** [comment]
Not an issue.

**Comment by hyberdk** [comment]
@ygorelik, what about ydk.io, you are referencing that as the website for the tool, but its not working anymore..

**Comment by ygorelik** [comment]
I corrected the link to [ciscodevnet.github.io/ydk-gen/](http://ciscodevnet.github.io/ydk-gen/).

**Comment by jillesca** [comment]
Hi, the repos below references to ydk.io too. is it possible to remove the ydk.io reference? if the repos are not supported anymore, probably is worth archive them.

https://github.com/CiscoDevNet/ydk-cpp
https://github.com/CiscoDevNet/ydk-py
https://github.com/CiscoDevNet/ydk-go

**Comment by ygorelik** [comment]
The listed repositories are not maintained anymore. 

I have removed references to ydk.io.
