### ISSUE TITLE
Add support for finding the Root Resource as specified by RFC 8040.

### ISSUE THREAD

**Issue by drewtoto** [CiscoDevNet/ydk-gen#1096]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
Correctly parse the Root Resource as specified by RESTCONF Protocol (RFC 8040) Section 3.1 from the "/.well-known/host-meta" resource when multiple &lt;Link> elements are present.  The Root Resource is determined by the &lt;Link> element that contains "rel='restconf'" attribute.

See https://datatracker.ietf.org/doc/html/rfc8040#section-3.1

Example response from "/.well-known/host-meta" with multiple &lt;Link>

> &lt;?xml version='1.0' encoding='UTF-8'?>
> &lt;XRD xmlns='http://docs.oasis-open.org/ns/xri/xrd-1.0'
> xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
>    &lt;Property type='http://example.org/example'>Example&lt; /Property>
>    &lt;Link rel='copyright' href='/copyright'/>
>    &lt;Link rel='restconf' type='application/yang-data+json' href='/restconf'/>
> &lt;/XRD>

## Current Behavior
The first &lt;Link> in the "/.well-known/host-meta" response is assumed to be the RESTCONF Root Resource without checking for the "rel='restconf'" attribute.

## Steps to Reproduce
1) Set up (build/install/etc) a YDK environment as specified by the documentation.
2) Acquire (or configure) a RESTCONF server that contains multiple <Link> attributes where the RESTCONF <Link> is not the first in the list.
3) Create an application that uses the YDK RestconfServiceProvider to connect to the server in step 2 (above).
4) Notice that the Root Resource used by the YDK RestconfServiceProvider client is taken from the first <Link>, not the correct &lt;Link> specifying the "rel='restconf'" attribute.

## Your Script

```
from __future__ import print_function
from ydk.providers import RestconfServiceProvider
from ydk.path import Repository
from ydk.types import EncodingFormat
import ydk

if __name__ == "__main__":
    provider = RestconfServiceProvider(repo=Repository(REPO_PATH), address=TARGET_IP, username=TARGET_USER, password=TARGET_PASSWORD, port=PORT, encoding=EncodingFormat.JSON)
```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

## System Information

Python 3.8.10
Ubuntu 20.04.6 LTS
Intel x86_64

**Comment by ygorelik** [comment]
Could you please open pull request to include your code changes to master branch.

**Comment by ygorelik** [comment]
Hello @drewtoto 

Could you please provide detail test description and results.

Does the introduced code affect YDK API?

Thank you.

**Comment by drewtoto** [comment]
Yes, I can work on a unit test.

The code does not affect the YDK API, it only fixes a bug (incomplete implementation) in the existing parsing code.
