### ISSUE TITLE
Encoding for leaflists produces elements with no data

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#127]
In the OpenConfig routing policy model, community members are generated with no data:
```
      <routing-policy xmlns="http://openconfig.net/yang/routing-policy">
        <defined-sets>
          <bgp-defined-sets xmlns="http://openconfig.net/yang/bgp-policy">
            <community-sets>
              <community-set>
                <community-set-name>COMMUNITY-SET1</community-set-name>
                <community-member></community-member>
              </community-set>
            </community-sets>
          </bgp-defined-sets>
        </defined-sets>
      </routing-policy>
```

The expected config is:
```
     <routing-policy xmlns="http://openconfig.net/yang/routing-policy">
        <defined-sets>
          <bgp-defined-sets xmlns="http://openconfig.net/yang/bgp-policy">
            <community-sets>
              <community-set>
                <community-set-name>COMMUNITY-SET1</community-set-name>
                <community-member>65172:16001</community-member>
              </community-set>
            </community-sets>
          </bgp-defined-sets>
        </defined-sets>
      </routing-policy>
```

**Comment by 111pontes** [comment]
Community members are defined as union of unions.  Nested definition seems to be creating the issue.  We should include this scenario in sanity tests.  Also, documentation generation needs to be validated.  Type for community members doesn't seem to be displayed correctly.

**Comment by abhikeshav** [comment]
In the [older version of openconfig bgp-types, which we are using](https://github.com/CiscoDevNet/ydk-gen/blob/master/profiles/ydk/yang/openconfig/bgp-types%402015-05-15.yang#L212), the bgp-well-known-community-type is defined as a string.

So the documentation seems ok for this

**Comment by 111pontes** [comment]
See:
![image](https://cloud.githubusercontent.com/assets/16885441/15486171/87c16546-20f8-11e6-89dd-4c856161a416.png)
