### ISSUE TITLE
Implement equality operator

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#128]
It'd be convenient to have the equality operators (`__eq__` and `__ne__`) implemented, so two objects can be easily compared.

```
bgp1 = bgp.Bgp()
bgp2 = bgp.Bgp()
if bgp1 == bgp2:
    pass
if bgp1 != bgp2:
    pass
```

**Comment by abhikeshav** [comment]
This is available from `0.6.0`
