### ISSUE TITLE
Reenable pygen_test

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#140]
Currently, since the classes are no longer alphabetically sorted, the model APIs are being generated in different order each time, so pygen_test is failing. Need to investigate why the APIs are in different order each time and fix it and reenable pygen_test

**Comment by psykokwak4** [comment]
Why we are not sorting classes? I added back this [line](https://github.com/CiscoDevNet/ydk-gen/pull/145/commits/8f8872adde49408a2db90385f6b1d7b8e7899ea3#diff-6b3b91b65d40b7ad38c129a9c16fa937R254), is this fix expected?

**Comment by abhikeshav** [comment]
Classes are no longer sorted as XR has some issues dealing with XML payload generated from sorted classes. This was found at 0.4.1 release time. So, the sorting was removed. However, somehow the classes are generated in different order every time generate.py is run, so pygen_test does not work. This may be a limitation of pyang, but I'm not sure. Need to investigate a fix to keep the same order of classes in generated API without sorting. This way, pygen_test can be reenabled

**Comment by psykokwak4** [comment]
ok, will disable pygen_test, and remove this line.

**Comment by abhikeshav** [comment]
A solution for this can be to provide an option (to be used for testing by pygen_test) to generate.py to sort the APIs to enable comparison between actual and generated APIs
