### ISSUE TITLE
Branching and versions

### ISSUE THREAD

**Issue by NathanDotTo** [CiscoDevNet/ydk-gen#143]
Hi

Are there any plans to create versioned releases and branches for ydk-gen? This would help us baseline our environment for reproducibility and automated testing purposes.

Many thanks

Nathan

**Comment by einarnn** [comment]
ydk-gen will get versioning, yes. This will most likely happen when we make it pip-installable. I think we should also start using git tags to identify stable labels.

Cheers,

Einar

**Comment by abhikeshav** [comment]
Being tracked by #82
