### ISSUE TITLE
Bundle documentation

### ISSUE THREAD

**Issue by psykokwak4** [CiscoDevNet/ydk-gen#148]
The current documentation for generated APIs binds with core library. In  [YDK 0.4.1 documentation](http://ydk.cisco.com/py/docs/) sidebar, we have cross referencing links between generated APIs and core library. We will lose connections if we generate documentation separately from core library. Current possible solutions are:
- Host different landing pages for different version of YDK core libraries.
- Manually maintain YDK landing pages and add links to newly generated bundle documentations.

We also need link in bundle documentation points back to core library documentation. Maybe we could add link in sidebar to corresponding YDK core library?
For instance, bundle `ydk_cisco_ios_xr` of version `0.1.0` uses core library version `0.4.1`, then the `YDK API` in sidebar will link to `http://ydk.cisco.com/py/docs/ydk.html?version=041`. And we also have link in landing page `http://ydk.cisco.com/py/docs?version=041` points to `http://ydk.cisco.com/py/docs/bundles/cisco-ios-xr?version=010`.

Any suggestions?

**Comment by abhikeshav** [comment]
<img width="1118" alt="screen shot 2016-08-16 at 9 43 21 am" src="https://cloud.githubusercontent.com/assets/17089095/17707592/ebdc9dae-6395-11e6-8f6a-57daa2cbdfde.png">
