### ISSUE TITLE
OC-BGP/OC-RPOL models have incorrect packaging

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#153]
All openconfig models except OC-BGP/OC-RPOL are currently packaged under:
ydk.models.openconfig.<model>
Packaging should be consistent for all OC models.

**Comment by abhikeshav** [comment]
This will be solved with bundles. The namespaces are proposed to be of the pattern:

ydk.models.<name of bundle>.<name of model>
