### ISSUE TITLE
Documentation should reference exact identity instead of base identity

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#161]
Documentation doesn't illustrate identity options for a given leaf.  It just provides stub information for the base identity.  In the oc-mpls model, options for tunnel type can't be discovered easily when navigating the LSP configuration tree:

![ydk-identity-doc1](https://cloud.githubusercontent.com/assets/16885441/16140097/af83aed2-3402-11e6-8392-54624bfc8c15.png)

![ydk-identity-doc](https://cloud.githubusercontent.com/assets/16885441/16140027/09cc403a-3402-11e6-8d6e-edc0081fd68e.png)

**Comment by abhikeshav** [comment]
YDK local validation can catch the error where base identity class is being instantiated and assigned to for such leafs. Can be a separate user story
