### ISSUE TITLE
pprint for YDK models

### ISSUE THREAD

**Issue by psykokwak4** [CiscoDevNet/ydk-gen#195]
From Nicolas Leiva,

> something that iterates through the full tree and pretty prints the data extracted from the network device.

Might need to iterate object using attribute names from i_meta.

**Comment by abhikeshav** [comment]
Similar solution is suggested in #71 . The code for this is on the yam branch of my fork

**Comment by 111pontes** [comment]
Codec service should meet this requirement.    We should extend to support JSON.
