### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#205]
Project needs to provide clear guidelines to facilitate contributions from others. A CONTRIBUTING file (or CONTRIBUTING.md if using Markdown) should be added to the root of your repository.  A link to the guide will be automatically added when a contributor creates an Issue or opens a Pull Request.

**Comment by abhikeshav** [comment]
Let me know if the below looks OK for a contribution/coding guide:

![screen shot 2016-09-16 at 10 28 12 am](https://cloud.githubusercontent.com/assets/17089095/18595147/4fb813ec-7bf8-11e6-95cf-5bf916cc6a8f.png)

![screen shot 2016-09-16 at 10 30 09 am](https://cloud.githubusercontent.com/assets/17089095/18595202/93977698-7bf8-11e6-9ffa-17d783b7f976.png)

**Comment by abhikeshav** [comment]
We can also look at the code-covenant project for example: https://github.com/ContributorCovenant/contributor_covenant

**Comment by abhikeshav** [comment]
Document added
