### ISSUE TITLE
need to support python virtual environment

### ISSUE THREAD

**Issue by siming85** [CiscoDevNet/ydk-gen#213]
the compilation of libnetconf (in both gen and the generated -py package) have hard-coded requirements to have:
`g++ -I/usr/include/python2.7 -I/usr/include/boost `

this should respect the fact that we could be in a python virtual environment (instead of hard-coded dependency to the system's virtual environment) and dynamically pull up this path instead.

**Comment by siming85** [comment]
fyi, this hard-coding also makes it failing compilation on Cisco CEL6 servers

**Comment by abhikeshav** [comment]
The native code installation/clone has been disabled with commit a88f70e8b666352728b43d79f34831fe14b4ebca. So the virtualenv installation should work now. The native code installation will be investigated in the background

**Comment by abhikeshav** [comment]
Closing the issue since virtualenv is now working
