### ISSUE TITLE
generated setup.py file mandates GitPython to be pre-installed

### ISSUE THREAD

**Issue by siming85** [CiscoDevNet/ydk-gen#214]
`from git import Repo`

inside setup.py file generated from ydk-gen

this is not a requirement on the ydk-py package

**Comment by abhikeshav** [comment]
ydk-py is currently on v0.4.2. It has not been updated to the latest generated python modules from ydk-gen. Once the update to the next planned release (v0.5.0) is done, both the setup.py will be reconciled

**Comment by abhikeshav** [comment]
Need to ensure that setup.py doesn't have any external dependencies (like GitPython) which are not part of requirements

**Comment by abhikeshav** [comment]
No longer an issue
