### ISSUE TITLE
cannot install the compiled package.. stuck in a loop and leaking memory

### ISSUE THREAD

**Issue by siming85** [CiscoDevNet/ydk-gen#215]
`Cleaning up...
Command ydk-test/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-WXf4uy-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-jsJ4YO-record/install-record.txt --single-version-externally-managed --compile --install-headers ydk-test/include/site/python2.7 failed with error code -9 in /tmp/pip-WXf4uy-build
Traceback (most recent call last):
  File "ydk-test/bin/pip", line 11, in <module>
    sys.exit(main())
  File "ydk-test/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 161: ordinal not in range(128)`

this is after using up ~ 15G of memory and stuck in a high CPU usage loop for a few minutes

**Comment by abhikeshav** [comment]
Has this issue been fixed with the latest code from master branch? I have no way of verifying this. Let me know. Thanks

**Comment by siming85** [comment]
this has been fixed indeed.
