### ISSUE TITLE
Need utilities for device capabilities

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#217]
API should expose device capabilities (including model details) and easily identify model version in the YDK package.

**Comment by einarnn** [comment]
On just the device capabilities piece, is tunneling out the "server capabilities" from the underlying netconf connection enough?

**Comment by 111pontes** [comment]
For device capabilities, it'd be good if we parsed the NETCONF capabilities and provided a dictionary, so you could easily iterate over models and reference their revision, etc.

**Comment by abhikeshav** [comment]
This is fixed in the upcoming YDK release `0.6.1`
