### ISSUE TITLE
Provide support for more service providers

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#22]
Candidates include
1. gRpc
2. Restconf

**Comment by lisroach** [comment]
+1 on gRPC. 

RESTconf will be good as well but not as pressing of a need.

**Comment by jbrentfoster** [comment]
+1 on RESTCONF

EPNM now has a RESTCONF NBI and we need to test it.  When can this be added?

Thanks,

**Comment by abhikeshav** [comment]
Thanks @lisroach, @jbrentfoster for your interest. We have planned to add support for these providers in the coming few months. Also note that, being an open-source project, we welcome contributions.

**Comment by abhikeshav** [comment]
Restconf provider added for C++
