### ISSUE TITLE
subclass ncclient.rpc.RPC and reducing code complexity

### ISSUE THREAD

**Issue by siming85** [CiscoDevNet/ydk-gen#224]
currently YDK calls directly `ncclient.rpc.RPC._request` method directly.

The code comment in `RPC()` class suggest that it should be subclassed and user should call the `request()` method instead. 

```
def request(self):
    """Subclasses must implement this method. Typically only the request needs to be built as an
    :class:`~xml.etree.ElementTree.Element` and everything else can be handed off to
    :meth:`_request`."""
    pass
```

This can improvise the coding around payload id replacement & handling.

**Comment by abhikeshav** [comment]
Closing as we are using c++ as core and ydk-py is now a wrapper around ydk-cpp
