### ISSUE TITLE
ydk.providers._proider_plugin._ClientSPPlugin could be a factory class

### ISSUE THREAD

**Issue by siming85** [CiscoDevNet/ydk-gen#225]
instead of using if logic:

```
if use_native_client:
    self.ydk_client = None
else:
    self._nc_manager = None
```

and etc throughout this implementation, creating a top-level netconf provider base class with subclassing would be ideal (for linear code flow)

Then you can write a factory function/class to dynamically pick the correct implementation.
kinda like this: http://python-3-patterns-idioms-test.readthedocs.io/en/latest/Factory.html

**Comment by abhikeshav** [comment]
_ClientSPPlugin is eventually going to be replaced with a class which wraps around C++ core. The existing code probably can be cleaned up to remove native provider code.
