### ISSUE TITLE
base service/provider classes missing standard interface

### ISSUE THREAD

**Issue by siming85** [CiscoDevNet/ydk-gen#226]
`ydk.provider.ServiceProvider` and `ydk.service.Service` base classes missing out standard methods for creating subclass implementations.

would be nice to have a standard interface where the encoding & decoding of YDK models are handled, and the user would only have to "fill in the blank" for custom service/provider implementation

**Comment by abhikeshav** [comment]
The issue with providing standard methods to be implemented for all services/providers is that every particular service/provider has different methods. It is difficult to define a set of common methods for providers across different protocols like netconf/restconf/gRPC. Same applies to services like CRUD service/netconf service/codec service.

Let me know if anyone has any thoughts about this proposal
