### ISSUE TITLE
make generate.py executable

### ISSUE THREAD

**Issue by siming85** [CiscoDevNet/ydk-gen#227]
add the following to generate.py

```
#!/bin/env python
```

and chmod +x to it will allow generate.py to run by itself.

**Comment by abhikeshav** [comment]
Submitted [pull request for this](https://github.com/CiscoDevNet/ydk-gen/pull/229). We will add a contribution guide soon, but feel free to submit pull requests for any fixes you see fit!

**Comment by abhikeshav** [comment]
fixed in a62276b19a917d154ace7baa383799cf2d70ffbf
