### ISSUE TITLE
Key-based access to list items

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#231]
In YDK-Py, YANG lists are currently implemented based on simple python lists.  It's not possible to access a particular item based on key(s).  This will be particularly useful when processing a long list of operational data (e.g. looking for a specific prefix in a long of prefixes).

 * [x] Python
 * [x] Go
 * [x] C++

**Comment by abhikeshav** [comment]
===Proposed fix===

Change `YList` to use `OrderedDict` in python and ordered map in Go

**Comment by abhikeshav** [comment]
* [x] Python
 * [ ] Go
 * [ ] C++
