### ISSUE TITLE
Define operations within service not as general types

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#236]
Currently READ() and DELETE() operations are defined as general types.  These operations need to be extended to support the full set defined by NETCONF (merge, replace, create, delete, remove).  Furthermore, these operations shouldn't be defined as general types (which seem unintuitive).  Instead they should be defined within the scope of the provider (NETCONF in this case).

**Comment by abhikeshav** [comment]
We now have `YFilter` in `0.6.0` to replace these objects
