### ISSUE TITLE
Local validation for NETCONF capabilities

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#243]
YDK should be able to perform local validation of NETCONF capabilities when a `NetconfService` operation is invoked.  These are some of the situations in which an exception could be raised locally without having to send any request to the NETCONF server:
- edit/copy config operation using running datastore as target when device didn't advertise the :writable-running capability
- edit/copy/lock/unlock config operation using candidate datastore as target, a commit/discard-changes operation being issued when device didn't advertise the :candidate capability
- confirmed/confirm-timeout/persist/persist-id option in commit operation or cancel-commit operation being issued when device didn't advertise the :confirmed-commit:1.1 capability

The main list of capabilities is available at:
https://tools.ietf.org/html/rfc6241#section-8

**Comment by abhikeshav** [comment]
Done in libyang in ydk new infra > `0.6.0`
