### ISSUE TITLE
NetconfService methods return XML string

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#253]
Current documentation for NetconfService methods describe as return parameter:

> Returns:    ok reply if operation succeeds else, raises an exception

On a closer look, the method returns the RPC reply verbatim as an string:

``` xml
<?xml version="1.0"?>
<rpc-reply message-id="urn:uuid:bf449698-7fcb-4a79-985a-8ed769ed005b" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
 <ok/>
</rpc-reply>
```

Given that we strive to abstract encoding and RPC details, it seems that returning `True` or an (OK) enum would be more appropriate.

**Comment by abhikeshav** [comment]
Fixed in ydk-cpp. Will be available in ydk-py once the porting is done
