### ISSUE TITLE
Proposal for YDK read/write API

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#255]
# Background

Currently, users of YDK are restricted in the way they can read/write data. For CRUD and Netconf service, users can only read/write an object, corresponding to only one yang module, at a time.

For example, the API usage looks something like the below:

``` python
bgp_filter = ydk.models.openconfig_bgp.Bgp()
bgp_read = crud.read(provider, bgp_filter) # bgp_read is of of ydk.models.openconfig_bgp.Bgp type

bgp_config = ydk.models.openconfig_bgp.Bgp()
crud.create(provider, bgp_config)
```

This is restrictive since users are able to only read an entity corresponding to one YANG module (openconfig-bgp) at a time.

To overcome this limitation and enable users to read/write entities corresponding to more than one YANG module, there are a few options:
# Options
## 1) list of entities

Provide a way to pass in list of entities and return a list of entities. Example would look something like the below:

``` python
bgp_filter = ydk.models.openconfig_bgp.Bgp()
router_policy_filter = ydk.models.openconfig_routing_policy.RoutingPolicy()
entity_list = crud.read(provider, [bgp_filter, router_policy_filter])

bgp_config = ydk.models.openconfig_bgp.Bgp()
router_policy_config = ydk.models.openconfig_routing_policy.RoutingPolicy()
crud.create(provider, [bgp_config, router_policy_config])
```

The disadvantage of this approach is that on the read, it is difficult to programmatically figure out the types of the elements of the returned list in the `read` operation. The advantage is that it is relatively easy to pass in a list of entities which are from different YANG modules.
## 2) dictionary of entities

Provide a way to pass in dictionary of entities and return a dictionary of entities. Example would look something like the below:

``` python
bgp_filter = ydk.models.openconfig_bgp.Bgp()
router_policy_filter = ydk.models.openconfig_routing_policy.RoutingPolicy()
entity_dict = crud.read(provider, {'openconfig-bgp':bgp_filter, 'openconfig-routing-policy':router_policy_filter})

bgp_config = ydk.models.openconfig_bgp.Bgp()
router_policy_config = ydk.models.openconfig_routing_policy.RoutingPolicy()
crud.create(provider, {'openconfig-bgp':bgp_config, 'openconfig-routing-policy':router_policy_config})
```

The disadvantage of this approach is that on the `create` operation, it is cumbersome to populate a dictionary of objects with all the keys. On the other hand, for the `read` operation, it is a lot easier to programmatically iterate through the dictionary and understand the entities returned.
## 3) top-level object

Provide a way to pass in a top-level object which contains an aggregation of entities and return a top-level object which contains an aggregation of entities. Example would look something like the below:

``` python
bgp_filter = ydk.models.openconfig_bgp.Bgp()
router_policy_filter = ydk.models.openconfig_routing_policy.RoutingPolicy()
filter = Filter([bgp_filter, router_policy_filter])
data = crud.read(provider, filter) # both this and below are accepted and are equivalent
data = crud.read(provider, [bgp_filter, router_policy_filter]) # both this and above are accepted and are equivalent

# returned data object is iterable across the contained aggregation of entities.
# A common method get_module_name() is provided to retrieve name of YANG module which they belong to:
for element in data:
    print element.get_module_name()

bgp_config = ydk.models.openconfig_bgp.Bgp()
router_policy_config = ydk.models.openconfig_routing_policy.RoutingPolicy()
config = Config([bgp_config, router_policy_config])
crud.create(provider, config) # both this and below are accepted and are equivalent
crud.create(provider, [bgp_config, router_policy_config]) # both this and above are accepted and are equivalent
```

This option takes the advantages of both option 1 and 2 above. Disadvantage is that an additional step is introduced when doing `create` to create a top-level object.
## 4) list of entities and a common method `get_module_name()` to retrieve YANG module name

Provide a way to pass in list of entities and return a list of entities. Example would look something like the below:

``` python
bgp_filter = ydk.models.openconfig_bgp.Bgp()
router_policy_filter = ydk.models.openconfig_routing_policy.RoutingPolicy()
entity_list = crud.read(provider, [bgp_filter, router_policy_filter])

# A common method get_module_name() is provided
# to retrieve name of YANG module which each element of list belongs to:
for element in entity_list:
    print element.get_module_name()

bgp_config = ydk.models.openconfig_bgp.Bgp()
router_policy_config = ydk.models.openconfig_routing_policy.RoutingPolicy()
crud.create(provider, [bgp_config, router_policy_config])
```

This option takes the advantages of both option 1 and 2 above.
# Different languages

The above proposals would apply to either python or C++
# Different services

The above proposals would apply to CRUD/Netconf service plus any future service we introduce

**Comment by psykokwak4** [comment]
Vote on option 4. And what about the entity_list is implemented as a dictionary so the user could iterate it through:
```python
for module_name, element in enumerate(entity_list):
    # Do something
```

**Comment by 111pontes** [comment]
We need to look at the work flow when you don't know what you're reading.  Basically, a read of the entire config (no filters specified).  Whatever abstraction we choose should allow you to easily:
- write a group of multiple configuration objects where each object would be a valid individual writable configuration 
- Read a group of objects (models) and easily
  - iterate over the group and identify the model associated with the object
  - reference a particular object by module name

**Comment by 4GOD** [comment]
I see this issue as closed. Is this somehow implemented to ydk-py? Thanks

**Comment by 111pontes** [comment]
It's been implemented in the new YDK infrastructure which is used by ydk-cpp.  The team is currently porting ydk-py to that infra.  Once that porting is completed, you'll be able to use the functionality in Python.
