### ISSUE TITLE
Support bundle file read and resolve YDK

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#26]
This issue tracks reading bundle files written in json and resolving all the models and bundles that are referenced in these files as per the ydk model in the metaservice branch

**Comment by psykokwak4** [comment]
Checked in a branch [xz-bundles](https://github.com/psykokwak4/ydk-gen/tree/xz-bundles), in the generate function in ydkgen/__init__.py, resolve_bundle will return an instance of YDKRepository, which contains folder for resolved modules.
