### ISSUE TITLE
Identities are not encoded correctly

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#266]
Identities are encoded empty in YDK 0.5.1.  The following statement:
```python
afi_safi_name = oc_bgp_types.Ipv4UnicastIdentity
```
is encoded as:
```xml
<afi-safi-name></afi-safi-name>
```
instead of the expected encoding:
```xml
<afi-safi-name xmlns:idx="http://openconfig.net/yang/bgp-types">idx:IPV4-UNICAST</afi-safi-name>
```

**Comment by abhikeshav** [comment]
It is working for the codec test on Travis CI (https://travis-ci.org/CiscoDevNet/ydk-py/jobs/166589148#L1374). What is the environment you are running in?

**Comment by 111pontes** [comment]
https://git.io/vPEOO

There's a patch that fixes it, but we should look at why current testing doesn't see an issue.

**Comment by 111pontes** [comment]
Closing this issue.  Identity class needed to be instantiated:

```python
afi_safi_name = oc_bgp_types.Ipv4UnicastIdentity()
```
