### ISSUE TITLE
NETCONF provider should check capabilities during local validation

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#273]
YDK local validation should throw an exception if the NETCONF server capabilities preclude the operation.  For example, when executing:
-  a `get`/`get-config`/`edit-config`/`copy-config` RPC with an entity/filter referencing a model not advertised in the capabilities
- a `commit` RPC or an RPC referencing the candidate datastore against a server not advertising the `:candidate` capability
- an `edit-config` RPC with `rollback-on-error` value in the `error-option` parameter against a server not advertising the `:rollback-on-error` capability
- a `validate` RPC or an `edit-config` RPC with `test-option` parameter against a server not advertising the `:validate` capability
- a `commit` RPC referencing confirmed-commit parameters (e.g. `confirmed`/`confirm-timeout`/`persist`) or a `cancel-commit` RPC against a sever not advertising  the `confirmed-commit:1.1` capability
- an `edit-config` RPC with running datastore against a server not advertising `:writable-running` capability
- an RPC referencing the startup datastore against a server not advertising the `:startup` capability
- an RPC with `url` element against a server not advertising the `:url` capability
- an RPC with an Xpath expression in a filter against a server not advertising the `:xpath` capability

Checks should follow definitions in [RFC 6261 Sec 8.](https://tools.ietf.org/html/rfc6241#section-8)

**Comment by abhikeshav** [comment]
Done in new ydk infra >`0.6.0`
