### ISSUE TITLE
Enhancement to ydk's CodecService for un-configuration payload

### ISSUE THREAD

**Issue by KunalKemburaj** [CiscoDevNet/ydk-gen#285]
We can collect the payload for configuring a feature, without sending to the device,

>>> from ydk.services import CodecService
>>> from ydk.providers import CodecServiceProvider
>>> from ydk.models import yyy
>>> provider = CodecServiceProvider(type="xml")
>>> codec = CodecService()
>>> ydk_obj = yyy.Native.Router.Ospf()
>>> ydk_obj.id = 200
>>> ydk_obj
<ydk.models.yyy.Native.Router.Ospf object at 0xf6ef208c>
>>> print(codec.encode(provider, ydk_obj))
<ospf xmlns="http://cisco.com/ns/yang/yyy/ios">
  <id>100</id>
</ospf> 

But it is not possible to get the payload for un-configuration with the ydk's codec service.
is there any other way of doing it with out sending to the device.?

**Comment by abhikeshav** [comment]
This is possible with C++ codec service , which has a wrapper in python (http://ydk.cisco.com/cpp/docs/api/services/codec_service.html)
