### ISSUE TITLE
Add Remove Operation

### ISSUE THREAD

**Issue by Jb00** [CiscoDevNet/ydk-gen#295]
At the moment, Ydk support Delete operation, but not Remove. It would be very useful, for example when shut/unshut an interface, doing twice shut at the moment return an exception, as you cannot do two delete in row.

But with Remove, this wouldn't raise an exception.

Thanks,

**Comment by 111pontes** [comment]
@Jb00, this is supported using the [NETCONF service](http://ydk.cisco.com/py/docs/ydk.services.html#netconfservice-provides-api-s-to-execute-netconf-operations).  You need to set the default_operation to remove in the edit_config method.

**Comment by 111pontes** [comment]
@Jb00, let me know if you found any issues using `remove` with the current implementation.  If there's none, we should close this issue. Thanks.

**Comment by Jb00** [comment]
I am not sure to understand;

I have my ydk_obj , and I have a field shutdown I want to remove. 

ydk_obj.shutdown = Remove() <-- this does not exists, of what I am aware.


How would I use the edit_config method ?

**Comment by abhikeshav** [comment]
Hi Jean-Benoit, I think Santiago is referring to the [edit_config function](http://ydk.cisco.com/py/docs/ydk.services.html#ydk.services.ydk.services.NetconfService.edit_config) of the NetconfService, to which we can pass in default_operation. However, [per the documentation for the DefaultOperation enum](http://ydk.cisco.com/py/docs/1e4d7d7f0e42401d0ba9e0e6f22df18e7ef49c16.html), remove is not one of the options supported, so I think your issue still needs a fix from YDK side.

**Comment by 111pontes** [comment]
My bad.  Yes, we're missing support for the remove operation whether CRUD or NETCONF service is used.  Remove isn't part of the options for `default-operation` in [RFC 6241](https://tools.ietf.org/html/rfc6241#section-7.2) for some reason

**Comment by Jb00** [comment]
Cool,  thanks for confirming.

**Comment by 111pontes** [comment]
Already tracked with https://github.com/CiscoDevNet/ydk-gen/issues/236
