### ISSUE TITLE
Ydk Log level should be debug

### ISSUE THREAD

**Issue by Jb00** [CiscoDevNet/ydk-gen#297]
To retrieve the string of the message which will be send to the device, it can be done like this:

```
    from ydk.types import Empty
    from ydk.models import ietf_netconf
    from ydk.services import CRUDService
    from ydk.services import CodecService
    from ydk.providers import CodecServiceProvider

    edit_config = ietf_netconf.EditConfigRpc()
    edit_config.input.target.running = Empty()
    edit_config.input.config = <your ydk obj>

    codec=CodecService()
    codec_p=CodecServiceProvider(type='xml')
    payload = codec.encode(codec_p, edit_config)

```
So now payload contains the string, however it also print to log as info message, the string. This is not needed, as the user already has it in the variable and he can decide if he wants it or not.

Right now,  I take it, examine it with my script, then send it to my device,   and it is printed many times in my log,  and makes it quite confusing for the user.

Sure I could modify your logger,  but I think instead in YDK, the log should be log.debug level, instead of info level

**Comment by abhikeshav** [comment]
fixed in ydk-cpp. Will be available in ydk-py once porting is complete
