### ISSUE TITLE
Classes should clearly identify the hierarchy they abstract

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#303]
At a very high level, a YANG model can define data, RPCs and notifications.  As YDK expands to support more and more RPCs and notifications, it is important to make the class documentation more explicit with respect to what the class is abstracting.  Currently, all data and RPC classes show `object` as a base.  We should consider whether the base class should be used to identify whether a given class abstracts a data, RPC or notification hierarchy.  If the base class isn't used for this purpose, the documentation should still clearly identify the abstraction.

In addition, YDK should preserve the integrity of node names instead of extending them to embed their type (a la [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation)).  Name integrity is important, so users can easily correlate the APIs with the output of other model tools (e.g. pyang, YANG explorer, etc).  The vast majority of class/member names maintain the name integrity with three exceptions: enums, identities and RPC.  For instance:
* [IsisInternalLevelEnum](http://ydk.cisco.com/py/docs/1d75f4b98a4c54908a11cbd0d9e163ac400f94a4.html) instead of IsisInternalLevel 
* [NopeerIdentity](http://ydk.cisco.com/py/docs/d9dcbc7ca8b7b757b652555eed5468b9284a29f1.html) instead of Nopeer
* [LogmsgRpc](http://ydk.cisco.com/py/docs/300a4171854404564decedec7ab13fe1036e5540.html) instead of Logmsg

This issue  is related to #290 which calls for better documentation of class members.

**Comment by psykokwak4** [comment]
Some code depend on the class name(`grep -r '__class__.__name__' path/to/ydk-gen/sdk`). I think we need to take them into consideration, for example, we could add different base classes for Enum, Identity, Rpc, before they are replaced by C++ core.

**Comment by 111pontes** [comment]
Issue #320 should be a subset of this issue.

**Comment by abhikeshav** [comment]
This is fixed in `0.6.0`
