### ISSUE TITLE
Improve performance of documentation generation

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#31]
From Xiaoqin:

> I read from this style guide: https://google.github.io/styleguide/pyguide.html#Strings
> Avoid using the + and += operators to accumulate a string within a loop. Since strings are immutable, this creates unnecessary temporary objects and results in quadratic rather than linear running time. Instead, add each substring to a list and ''.join the list after the loop terminates (or, write each substring to a io.BytesIO buffer).
```python
Yes: items = ['<table>']
     for last_name, first_name in employee_list:
         items.append('<tr><td>%s, %s</td></tr>' % (last_name, first_name))
     items.append('</table>')
     employee_table = ''.join(items)
```
```python
No: employee_table = '<table>'
    for last_name, first_name in employee_list:
        employee_table += '<tr><td>%s, %s</td></tr>' % (last_name, first_name)
    employee_table += '</table>'
```

> By changing += and + operators to list join, it might increase the speed for documentation.

**Comment by ylil93** [comment]
Another possible improvement:
Right now, the way we write to a file is by calling write() for each new line, but it might be more efficient to put all lines into a list object and then call write() one time to reduce i/o overhead

**Comment by abhikeshav** [comment]
Yes. Sounds like a good idea.
