### ISSUE TITLE
generate.py failure is blocking critical demo

### ISSUE THREAD

**Issue by mdear** [CiscoDevNet/ydk-gen#327]
I'm installing YDK for the first time and must test against an IOS-XE-Polaris CSR1000V device to prepare for a business critical demo.  I'm using a loadset from Nov 23/16  (/uto/ssr-sjc-backup/IMAGES/BLD-BLD_POLARIS_DEV_LATEST_20161123_081342_ultra.ova)

After bringing up and configuring the device I then selected the ned model from YTOOL and downloaded from YTOOL a zipfile containing this model and all its dependent models (pulled from the device by YTOOL).

I'm following the instructions shown to install YDK:
https://wiki.cisco.com/display/PYATS/YDK

Please provide a fix or workaround.

My bundle JSON:
{
    "name": "XE_CSR_Polaris",
    "version": "1.0.0",
    "author": "Cisco",
    "copyright": "Cisco",
    "description": "Cisco IOS-XE Native Models From Git",
    "models": {
        "git": [
        {
        "url": "/nobackup/mdear/pyats_release_dev/models/",
        "commits": [
            {
            "commitid": "ed79558ccca5ded441aa5a8bb7e40cc5a041e41d",
            "dir": [
                "/"
            ]
            }
        ]
        }
        ]
    }
}

Symptoms:
[pyats_release_dev] asg-lnx-1:311> pwd
/nobackup/mdear/pyats_release_dev/ydk-gen

[pyats_release_dev] asg-lnx-1:310> ./generate.py --python --bundle /nobackup/mdear/pyats_release_dev/ydk-gen/profiles/bundles/mdear.json --verbose
YDKGEN_HOME not set. Assuming current directory is working directory.
Bundle Translator: Cloning from /nobackup/mdear/pyats_release_dev/models/ --> /tmp/tmp_2e4fc9i.yang
Bundle Translator: Removing folder /tmp/tmp_2e4fc9i.yang
Resolving file tmpjna55hno.bundle --> /nobackup/mdear/pyats_release_dev/ydk-gen/gen-api/.cache/bundles
Copying /nobackup/mdear/pyats_release_dev/ydk-gen/sdk/python/packages to /nobackup/mdear/pyats_release_dev/ydk-gen/gen-api/python/XE_CSR_Polaris-bundle
Traceback (most recent call last):
  File "./generate.py", line 305, in <module>
    'bundle').generate(options.bundle))
  File "/nobackup/mdear/pyats_release_dev/ydk-gen/ydkgen/__init__.py", line 87, in generate
    return self._generate_bundle(description_file)
  File "/nobackup/mdear/pyats_release_dev/ydk-gen/ydkgen/__init__.py", line 116, in _generate_bundle
    self._print_pkgs(api_pkgs, gen_api_root, curr_bundle.name)
  File "/nobackup/mdear/pyats_release_dev/ydk-gen/ydkgen/__init__.py", line 168, in _print_pkgs
    ydk_printer.emit(pkgs)
  File "/nobackup/mdear/pyats_release_dev/ydk-gen/ydkgen/printer/language_bindings_printer.py", line 62, in emit
    self.print_files()
  File "/nobackup/mdear/pyats_release_dev/ydk-gen/ydkgen/printer/python/python_bindings_printer.py", line 57, in print_files
    self.print_nmsp_augment_finder_init(os.path.join(self.sub_dir, '_meta'), True)
  File "/nobackup/mdear/pyats_release_dev/ydk-gen/ydkgen/printer/python/python_bindings_printer.py", line 182, in print_nmsp_augment_finder_init
    _EmitArgs(self.ypy_ctx, self.packages, is_meta))
  File "/nobackup/mdear/pyats_release_dev/ydk-gen/ydkgen/printer/language_bindings_printer.py", line 91, in print_file
    with open(path, 'w+') as file_descriptor:
FileNotFoundError: [Errno 2] No such file or directory: '/nobackup/mdear/pyats_release_dev/ydk-gen/gen-api/python/XE_CSR_Polaris-bundle/ydk/models/XE_CSR_Polaris/_meta/__init__.py'

The zipfile is available at the following Cisco-internal location:

/ws/mdear-ott/Downloads/schema-2016-12-09-19_01_01.zip

**Comment by 111pontes** [comment]
The syntax of your bundle profile is incorrect.  The following profile gives you an idea of how to reference local files:
https://github.com/CiscoDevNet/ydk-gen/blob/master/profiles/bundles/openconfig_0_1_0.json
