### ISSUE TITLE
RPC output data should also be rendered as classes with proper validation

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#332]
Currently, the [ExecutorService documentation](http://ydk.cisco.com/py/docs/ydk.services.html#executorservice-provides-api-to-execute-rpcs) indicates that the `execute_rpc` method doesn't return any value.  However, many RPCs define output data.  This method should return a validated entity for those RPCs.

**Comment by networkop** [comment]
+1 for this feature. Should it be possible to decode the received response manually in the meantime? With something like codec.decode(provider,xml)?

**Comment by abhikeshav** [comment]
Hi, this feature is being implemented in the new core infrastructure and will be available soon. In the meanwhile, yes, you can use the codec_service.decode function for decoding the returned XML payload

**Comment by 111pontes** [comment]
I don't think codec service can be seamlessly used.  Returned string contains the raw NETCONF RPC reply.  XML string has be to manipulated to remove `rpc-reply` tag.  Otherwise, data validation would fail.

**Comment by abhikeshav** [comment]
For RPCs which don't define `output` data, like `edit-config`, which returns `<ok/>` on success, the return value would be `None`. Just want to make sure this makes sense.

**Comment by 111pontes** [comment]
There are at least four possible scenarios:
1. RPC succeeds and no data is returned and model specifies data (e.g. oper data non-existent) 
2. RPC succeeds, no data is returned and model specifies no data (e.g. RPC w/o output)
3. RPC succeeds and data is returned
4. RPC fails

Yes, it seems sensible that 1, 2 and 4 return `None` and exception handling is used to manage failure scenarios.
