### ISSUE TITLE
Can't generate C++ share library with cmake 2.8

### ISSUE THREAD

**Issue by briancui** [CiscoDevNet/ydk-gen#340]
Processing 96 of 96 /home/dev01/confd-6.1/yang/ydk-gen-master/gen-api/.cache/models/rv340@0.1.0/ciscosb-syslog.yang
 
Time taken for code/doc generation:  6 seconds
 
 
Building cpp package...
 
CMake Error at CMakeLists.txt:2 (cmake_policy):
  Policy "CMP0048" is not known to this version of CMake.
 
 
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_VERSION_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_VERSION_COMPILER
CMake Error: Could not find cmake module file: /home/dev01/confd-6.1/yang/ydk-gen-master/gen-api/cpp/rv340-bundle/build/CMakeFiles/2.8.12.2/CMakeVERSIONCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_0.5.2_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_0.5.2_COMPILER
CMake Error: Could not find cmake module file: /home/dev01/confd-6.1/yang/ydk-gen-master/gen-api/cpp/rv340-bundle/build/CMakeFiles/2.8.12.2/CMake0.5.2Compiler.cmake
CMake Error: Could not find cmake module file: CMakeVERSIONInformation.cmake
CMake Error: Could not find cmake module file: CMake0.5.2Information.cmake
CMake Error: CMAKE_VERSION_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_0.5.2_COMPILER not set, after EnableLanguage
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBYDK_INCLUDE_DIR
   used as include directory in directory /home/dev01/confd-6.1/yang/ydk-gen-master/gen-api/cpp/rv340-bundle
   used as include directory in directory /home/dev01/confd-6.1/yang/ydk-gen-master/gen-api/cpp/rv340-bundle
LIBYDK_LIBRARY
    linked by target "ydk_rv340" in directory /home/dev01/confd-6.1/yang/ydk-gen-master/gen-api/cpp/rv340-bundle
 
-- Configuring incomplete, errors occurred!
See also "/home/dev01/confd-6.1/yang/ydk-gen-master/gen-api/cpp/rv340-bundle/build/CMakeFiles/CMakeOutput.log".
 
ERROR: Failed to create shared library!

**Comment by psykokwak4** [comment]
Have you installed core?
```bash
$ python generate.py --core --cpp
$ cd gen-api/cpp/ydk/build
$ sudo make install

```

**Comment by briancui** [comment]
Yes, I compiled the core, and got compile error:

/home/dev01/confd-6.1/yang/ydk-gen-master/sdk/cpp/core/src/ietf_netconf.cpp:182:12: error: 'make_unique' is not a member of 'std'

already raised another issue to track it.

**Comment by psykokwak4** [comment]
Thanks for raising #342,  the CMake error message above complains about not able to find libydk. It should work if libydk is able to be compiled and installed.

**Comment by dummyuser1984** [comment]
iam facing the same compilation issue..what is the resolution for this?

**Comment by abhikeshav** [comment]
Please try using newer cmake (>3.7) as a workaround for this

**Comment by dummyuser1984** [comment]
Thanks Compilation worked after upgrading cmake
