### ISSUE TITLE
Netconf key elements are not serialized in specified order

### ISSUE THREAD

**Issue by wabain** [CiscoDevNet/ydk-gen#363]
The Python SDK places list keys before other elements when generating Netconf XML, but always sorts the key elements in alphabetical order. This behavior can cause XML generated by ydk by Cisco's ConfD.

The expected behavior is specified in RFCs [6020](https://tools.ietf.org/html/rfc6020#page-70) and [7950](https://tools.ietf.org/html/rfc7950#page-88), which state that:

> The list's key nodes are encoded as subelements to the list's
  identifier element, in the same order as they are defined within the
  "key" statement.

Sample case, tested with 0.5.2 and master (cb522de4fa219ceb55945f09c6088091d0fb61cc):

`ydk-id-order-bug.yang`

```yang
module ydk-id-order-bug {
  namespace "http://example.org/ns/yang/ydk-id-order-bug";
  prefix "order-bug";

  list multi-key-list {
    key "c b";

    leaf a { type uint32; }
    leaf b { type uint32; }
    leaf c { type uint32; }
  }
}
```

Bundle file: `ydk-id-order-bug.json`

```json
{
   "name": "ydk-id-order-bug",
   "version": "0.1.0",
   "ydk_version": "0.5.2",
   "models": {
       "file": [
           "ydk-id-order-bug.yang"
       ]
   }
}
```

Sample usage:

```python
from ydk.providers import CodecServiceProvider
from ydk.services import CodecService

from ydk.models.ydk_id_order_bug.ydk_id_order_bug import MultiKeyList

model = MultiKeyList()

model.a = 1
model.b = 2
model.c = 3

svc = CodecService()
sp = CodecServiceProvider(type='xml')

print(svc.encode(sp, model))

## Output:
# <multi-key-list xmlns="http://example.org/ns/yang/ydk-id-order-bug">
#   <b>2</b>
#   <c>3</c>
#   <a>1</a>
# </multi-key-list>

## Expected output:
# <multi-key-list xmlns="http://example.org/ns/yang/ydk-id-order-bug">
#   <c>3</c>
#   <b>2</b>
#   <a>1</a>
# </multi-key-list>
```

**Comment by abhikeshav** [comment]
This will be fixed in the new YDK-Py infrastructure (ydk 0.6.0)
