### ISSUE TITLE
Missing local validation for static route prefixes

### ISSUE THREAD

**Issue by marumer** [CiscoDevNet/ydk-gen#385]
Hi,
Working on a presentation focused on a value of local validation, I create a wrong ip prefix for a static route but I keep receiving a ydk.errors.YPYServiceProviderError instead of a ydk.errors.YPYDataValidationError  and I have confirmed below that the message comes from the Netconf server. I have tried obvious wrong string like <prefix>1.1.1???</prefix>, with the same result ... no local validation.

This is the code:
router_static = xr_ip_static_cfg.RouterStatic() 
vrf_unicast = router_static.default_vrf.address_family.vrfipv4.vrf_unicast
vrf_prefix = vrf_unicast.vrf_prefixes.VrfPrefix()
**vrf_prefix.prefix = "1.1.1.A"   # Note that this is a wrong IP address**
vrf_prefix.prefix_length = 24
vrf_next_hop_next_hop_address = vrf_prefix.vrf_route.vrf_next_hop_table.VrfNextHopNextHopAddress()
vrf_next_hop_next_hop_address.next_hop_address = "192.168.10.5"
vrf_prefix.vrf_route.vrf_next_hop_table.vrf_next_hop_next_hop_address.append(vrf_next_hop_next_hop_address)
vrf_unicast.vrf_prefixes.vrf_prefix.append(vrf_prefix)

and the logging:
CREATE operation initiated
 
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:f95418a8-7769-42cf-bd0d-c0ead32daeb2">
  <edit-config>
    <target>
      <candidate/>
    </target>
    <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
      <router-static xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ip-static-cfg">
        <default-vrf>
          <address-family>
            <vrfipv4>
              <vrf-unicast>
                <vrf-prefixes>
                  <vrf-prefix>
                    <prefix>1.1.1.A</prefix>
                    <prefix-length>24</prefix-length>
                    <vrf-route>
                      <vrf-next-hop-table>
                        <vrf-next-hop-next-hop-address>
                          <next-hop-address>192.168.10.5</next-hop-address>
                        </vrf-next-hop-next-hop-address>
                      </vrf-next-hop-table>
                    </vrf-route>
                  </vrf-prefix>
                </vrf-prefixes>
              </vrf-unicast>
            </vrfipv4>
          </address-family>
        </default-vrf>
      </router-static>
    </config>
  </edit-config>
</rpc>
 
 
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:f95418a8-7769-42cf-bd0d-c0ead32daeb2">
  <edit-config>
    <target>
      <candidate/>
    </target>
    <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
      <router-static xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ip-static-cfg">
        <default-vrf>
          <address-family>
            <vrfipv4>
              <vrf-unicast>
                <vrf-prefixes>
                  <vrf-prefix>
                    <prefix>1.1.1.A</prefix>
                    <prefix-length>24</prefix-length>
                    <vrf-route>
                      <vrf-next-hop-table>
                        <vrf-next-hop-next-hop-address>
                          <next-hop-address>192.168.10.5</next-hop-address>
                        </vrf-next-hop-next-hop-address>
                      </vrf-next-hop-table>
                    </vrf-route>
                  </vrf-prefix>
                </vrf-prefixes>
              </vrf-unicast>
            </vrfipv4>
          </address-family>
        </default-vrf>
      </router-static>
    </config>
  </edit-config>
</rpc>
 
 
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:f95418a8-7769-42cf-bd0d-c0ead32daeb2">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>bad-element</error-tag>
    <error-severity>error</error-severity>
    <error-path xmlns:ns1="http://cisco.com/ns/yang/Cisco-IOS-XR-ip-static-cfg">ns1:router-static/ns1:default-vrf/ns1:address-family/ns1:vrfipv4/ns1:vrf-unicast/ns1:vrf-prefixes/ns1:vrf-prefix[prefix = '1.1.1.A' and prefix-length = '24']/ns1:prefix</error-path>
    <error-info>
      <bad-element>prefix</bad-element>
    </error-info>
  </rpc-error>
</rpc-reply>

CREATE operation completed

**Comment by 111pontes** [comment]
The current release of YDK-Py (0.5.3) may miss some regular expression checks depending on the pattern involved.  The new YDK-Py infrastructure (expected to be in 0.6.0) will take care of these issues.
