### ISSUE TITLE
pycrypto/pycryptodome package collision, please investigate YDK implementations/workaround

### ISSUE THREAD

**Issue by mdear** [CiscoDevNet/ydk-gen#389]
We have a package collision between pycrypto and pycryptodome.

from paramiko import util
    from Crypto.Util.asn1 import (DerSequence, DerInteger, DerBitString,
ImportError: cannot import name 'DerBitString'

pycryptodome appears to be overwriting parts of site-packages/Crypto, which is the same place pycrypto installs into, with alpha content that has not yet been released by the pycrypto owners.

Can ydk operate with the beta-version pycrypto package that comes with pycryptodome ?

Collecting pycrypto==2.6.1 (from ydk==0.5.2)
	- This package writes to the "Crypto" directory and appears to collide with

pycryptodome (from pysnmp->uniclean>=2.2.0->dyntopo)
	- Which appears to incorporate a newer (alpha) version of pycrypto 2.7a1 that conflicts with pycrypto.

https://www.dlitz.net/software/pycrypto/

https://pycryptodome.readthedocs.io/en/latest/src/changelog.html 

Workaround (but will this work with YDK?): 
pip uninstall pycrypto pycryptodome
pip install pycryptodome

**Comment by abhikeshav** [comment]
This is more of a ncclient issue as YDK just uses ncclient as it is, as of now. However, [in the future release](https://github.com/CiscoDevNet/ydk-gen/wiki/ydk-cpp-core-for-multi-language-bindings-support), we may get rid of ncclient dependency.

**Comment by mdear** [comment]
Then, why is pycrypto mentioned explicitly in your setup.py INSTALL_REQUIREMENTS alongside ncclient ?    It pycrypto truly required by YDK today ?

**Comment by abhikeshav** [comment]
You are right. The current day YDK-Py does not directly need to install pcrypto.  The right version of it will be automatically grabbed by ncclient. [This commit](9166283d76362fece8413f4c770bb771c039b53e) removes indirect dependencies of ydk. So the dependencies are now:
```
                        'enum34==1.1.3',
                        'lxml==3.4.4',
                        'pyang==1.6',
                        'ncclient>=0.4.7',
                        'pybind11==2.0.1'
```

**Comment by mdear** [comment]
Please see the comment I raised against this commit.

Thanks
<Myles>

Sent from my iPhone

On Feb 27, 2017, at 2:17 PM, Abhi Keshav <notifications@github.com<mailto:notifications@github.com>> wrote:


You are right. The current day YDK-Py does not directly need to install pcrypto. The right version of it will be automatically grabbed by ncclient. This commit<9166283d76362fece8413f4c770bb771c039b53e> removes indirect dependencies of ydk. So the dependencies are now:

                        'enum34==1.1.3',
                        'lxml==3.4.4',
                        'pyang==1.6',
                        'ncclient>=0.4.7',
                        'pybind11==2.0.1'


-

**Comment by abhikeshav** [comment]
Thanks will be fixed in next commit

**Comment by mdear** [comment]
Great, thanks for following up.  YDK was working for me with a brand new install with these changes.
