### ISSUE TITLE
Broken leaf-lists (maybe other lists) in IOS-XR cause failures in YDK code

### ISSUE THREAD

**Issue by einarnn** [CiscoDevNet/ydk-gen#394]
We're now starting to see multiple instances of broken leaf-lists in IOS-XR causing failures on operational data retrieval, such as [this issue](https://communities.cisco.com/message/247420) on the YDK developer forum.

We should probably allow such data to be parsed into Python objects as it can be successfully retrieved over plain netconf. Also, we load the data into lists, so it is practical to allow duplicate values, even though they are technically disallowed by YANG.

**Comment by 111pontes** [comment]
Duplicate entries in a leaf list are a violation of RFC 6020 ("The values in a leaf-list MUST be unique.").  It's a good thing that YDK validation throws an exception.  We are tracking issue #381 to allow users to easily access the XML as exception data in case they want to continue processing the data despite validation errors.
