### ISSUE TITLE
Please rectify incomplete fix to issue #389 (remove indirect dependencies)

### ISSUE THREAD

**Issue by mdear** [CiscoDevNet/ydk-gen#396]
In response to the following issue:
pycrypto/pycryptodome package collision, please investigate YDK implementations/workaround #389
https://github.com/CiscoDevNet/ydk-gen/issues/389

The following commit was made:
remove indirect dependencies for ydk-py and ydk-gen (#392) 
https://github.com/CiscoDevNet/ydk-gen/commit/9166283d76362fece8413f4c770bb771c039b53e

However, the commit was incomplete, this issue tracks the comment I made against the commit:
May I suggest that you also make the same change in sdk/python/packages/setup.py ?

**Comment by abhikeshav** [comment]
This has actually been fixed in the next commit. See this [line](https://github.com/CiscoDevNet/ydk-gen/blob/master/sdk/python/packages/setup.py#L27) :)

**Comment by mdear** [comment]
Great, thanks for confirming this.
