### ISSUE TITLE
Some enum documentation isn't generated correctly

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#40]
For instance, documentation for enums in Cisco_IOS_XR_ip_ntp_cfg is generated correctly.  However, documentation for enums in Cisco_IOS_XR_clns_isis_cfg module points to a non-existent files.

**Comment by ylil93** [comment]
Hi Santiago, I noticed that the number of typedef statements and top level container statements in the Cisco_IOS_XR_clns_isis_cfg yang file matches the number of links in the corresponding document (looking at ydk.cisco.com)

I believe this is the expected behavior
