### ISSUE TITLE
YDK-Cpp debian packaging not handling dependencies

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#413]
Installing the package for a model bundle should trigger the installation of:
* system dependencies
* YDK core package
* All other bundle dependencies
Current packaging is not handling dependencies.

**Comment by abhikeshav** [comment]
The following steps automatically installs dependencies of libydk
```
$ wget https://devhub.cisco.com/artifactory/debian-ydk/0.5.5/libydk_0.5.5-1_amd64.deb
$ sudo apt-get install gdebi-core
$  sudo gdebi libydk_0.5.5-1_amd64.deb
```
