### ISSUE TITLE
CodecService decode method correct usage

### ISSUE THREAD

**Issue by networkop** [CiscoDevNet/ydk-gen#421]
I'm trying to decode a payload previously generated by CodecService's encode method and I'm getting KeyError exception all of the time. What am I doing wrong?   
Here's example for native yang model's bgp config:
```python
from ydk.models.cisco_ios_xe.ned import Native
from ydk.providers import CodecServiceProvider
from ydk.services import CodecService
bgp = Native().router.Bgp()
bgp.id = 100
n = bgp.Neighbor()
n.id = '2.2.2.2'
n.remote_as = 65100
bgp.neighbor.append(n)
provider = CodecServiceProvider(type="xml")
codec = CodecService()
xml = codec.encode(provider, bgp)
model = codec.decode(provider, xml)
```
This is the full tracepback:
```python
KeyError                                  Traceback (most recent call last)
<ipython-input-10-0f05e93962db> in <module>()
----> 1 model = codec.decode(provider, xml)

/usr/lib/python2.7/site-packages/ydk/services/codec_service.pyc in decode(self, decoder, payload)
     47             raise YPYServiceError(error_msg=msg)
     48         self.service_logger.info('Decoding operation initiated')
---> 49         entity = self.operate_on_object_or_dictionary(payload, CodecService._decode_payload, [decoder])
     50         self.service_logger.info('Decoding operation completed')
     51         return entity

/usr/lib/python2.7/site-packages/ydk/services/service.pyc in operate_on_object_or_dictionary(self, entity, function, args)
     30                 result[module] = function(child, *args)
     31         else:
---> 32             result = function(entity, *args)
     33         return result
     34

/usr/lib/python2.7/site-packages/ydk/services/codec_service.pyc in _decode_payload(payload, decoder)
     53     @staticmethod
     54     def _decode_payload(payload, decoder):
---> 55         entity = decoder._decode(payload)
     56         return entity
     57

/usr/lib/python2.7/site-packages/ydk/providers/codec_provider.pyc in _decode(self, payload)
     63         """ Decodes the payload from the desired decoding format """
     64         self.logger.info('Decoding payload: {0}'.format(payload))
---> 65         entity = self.decoder.decode(payload)
     66         self.logger.info('Result of decoding: {0}'.format(entity))
     67         return entity

/usr/lib/python2.7/site-packages/ydk/providers/_decoder.pyc in decode(self, payload)
     38     def decode(self, payload):
     39         payload_tree = etree.fromstring(payload.encode('utf-8'))
---> 40         top_entity = self._get_top_entity(payload_tree)
     41         rt = payload_tree.getroottree().getroot()
     42         curr_rt = get_root(rt, top_entity, _yang_ns._namespaces)

/usr/lib/python2.7/site-packages/ydk/providers/_decoder.pyc in _get_top_entity(self, payload_tree)
     57         root = payload_tree.getroottree().getroot()
     58         namespace = root.tag.split('}')[0][1:]
---> 59         return self.get_top_container_for_namespace(namespace, root.tag.split('}')[1])
     60
     61     @staticmethod

/usr/lib/python2.7/site-packages/ydk/providers/_decoder.pyc in get_top_container_for_namespace(self, namespace, text)
     49
     50     def get_top_container_for_namespace(self, namespace, text):
---> 51         entity_import = _yang_ns._namespace_package_map[(namespace, text)]
     52         exec(entity_import)
     53         top_entity = eval('%s()' % entity_import.split()[-1])

KeyError: ('http://cisco.com/ns/yang/ned/ios', 'bgp')
```

**Comment by abhikeshav** [comment]
Hi,
Can you please enable logging and post the log?

http://ydk.cisco.com/py/docs/introduction.html#logging



On Mar 25, 2017 1:32 PM, networkop <notifications@github.com> wrote:

I'm trying to decode a payload previously generated by CodecService's encode method and I'm getting KeyError exception all of the time. What am I doing wrong?
Here's example for native yang model's bgp config:

from ydk.models.cisco_ios_xe.ned import Native
from ydk.providers import CodecServiceProvider
from ydk.services import CodecService
bgp = Native().router.Bgp()
bgp.id = 100
n = bgp.Neighbor()
n.id = '2.2.2.2'
n.remote_as = 65100
bgp.neighbor.append(n)
provider = CodecServiceProvider(type="xml")
codec = CodecService()
xml = codec.encode(provider, bgp)
model = codec.decode(provider, xml)

This is the full tracepback:

KeyError                                  Traceback (most recent call last)
<ipython-input-10-0f05e93962db> in <module>()
----> 1 model = codec.decode(provider, xml)

/usr/lib/python2.7/site-packages/ydk/services/codec_service.pyc in decode(self, decoder, payload)
     47             raise YPYServiceError(error_msg=msg)
     48         self.service_logger.info('Decoding operation initiated')
---> 49         entity = self.operate_on_object_or_dictionary(payload, CodecService._decode_payload, [decoder])
     50         self.service_logger.info('Decoding operation completed')
     51         return entity

/usr/lib/python2.7/site-packages/ydk/services/service.pyc in operate_on_object_or_dictionary(self, entity, function, args)
     30                 result[module] = function(child, *args)
     31         else:
---> 32             result = function(entity, *args)
     33         return result
     34

/usr/lib/python2.7/site-packages/ydk/services/codec_service.pyc in _decode_payload(payload, decoder)
     53     @staticmethod
     54     def _decode_payload(payload, decoder):
---> 55         entity = decoder._decode(payload)
     56         return entity
     57

/usr/lib/python2.7/site-packages/ydk/providers/codec_provider.pyc in _decode(self, payload)
     63         """ Decodes the payload from the desired decoding format """
     64         self.logger.info('Decoding payload: {0}'.format(payload))
---> 65         entity = self.decoder.decode(payload)
     66         self.logger.info('Result of decoding: {0}'.format(entity))
     67         return entity

/usr/lib/python2.7/site-packages/ydk/providers/_decoder.pyc in decode(self, payload)
     38     def decode(self, payload):
     39         payload_tree = etree.fromstring(payload.encode('utf-8'))
---> 40         top_entity = self._get_top_entity(payload_tree)
     41         rt = payload_tree.getroottree().getroot()
     42         curr_rt = get_root(rt, top_entity, _yang_ns._namespaces)

/usr/lib/python2.7/site-packages/ydk/providers/_decoder.pyc in _get_top_entity(self, payload_tree)
     57         root = payload_tree.getroottree().getroot()
     58         namespace = root.tag.split('}')[0][1:]
---> 59         return self.get_top_container_for_namespace(namespace, root.tag.split('}')[1])
     60
     61     @staticmethod

/usr/lib/python2.7/site-packages/ydk/providers/_decoder.pyc in get_top_container_for_namespace(self, namespace, text)
     49
     50     def get_top_container_for_namespace(self, namespace, text):
---> 51         entity_import = _yang_ns._namespace_package_map[(namespace, text)]
     52         exec(entity_import)
     53         top_entity = eval('%s()' % entity_import.split()[-1])

KeyError: ('http://cisco.com/ns/yang/ned/ios', 'bgp')

**Comment by networkop** [comment]
here's the log:
Encoding operation initiated
Result of encoding:
<bgp xmlns="http://cisco.com/ns/yang/ned/ios">
  <id>100</id>
  <neighbor>
    <id>2.2.2.2</id>
    <remote-as>65100</remote-as>
  </neighbor>
</bgp>

Encoding operation completed
Decoding operation initiated
Decoding payload: <bgp xmlns="http://cisco.com/ns/yang/ned/ios">
  <id>100</id>
  <neighbor>
    <id>2.2.2.2</id>
    <remote-as>65100</remote-as>
  </neighbor>
</bgp>

**Comment by abhikeshav** [comment]
Thanks for posting the log. Looks like you are trying to encode the child container `native > router > bgp`. However, the `CodecService` expects the top-level containers to be passed in. Can you try changing your script to the below:

```python
from ydk.models.cisco_ios_xe.ned import Native
from ydk.providers import CodecServiceProvider
from ydk.services import CodecService

native = Native()
bgp = native.router.Bgp()
native.router.bgp = bgp
bgp.id = 100
n = bgp.Neighbor()
n.id = '2.2.2.2'
n.remote_as = 65100
bgp.neighbor.append(n)
provider = CodecServiceProvider(type="xml")
codec = CodecService()
xml = codec.encode(provider, native)
model = codec.decode(provider, xml)
```

**Comment by networkop** [comment]
Excellent, it worked! Thank you. 
Just out of curiosity - how does decoder know exactly which model to instantiate? Does it search the global namespace for object matching the root XML element, meaning I have to have it imported before I can use a decoder?

**Comment by abhikeshav** [comment]
Glad it worked. You're right about the decoder searching global namespaces to match the top XML element. It then returns the object of the correct type. The type doesn't have to imported beforehand by the user.

**Comment by networkop** [comment]
Cool. thanks for your help
