### ISSUE TITLE
When the ietf augumented custom bundles are built in YDK-gen, memory overflow and IndexError issues are seen.

### ISSUE THREAD

**Issue by mailravi02** [CiscoDevNet/ydk-gen#438]
Root cause Analysis:
   When YDK-gen is built with augmented ietf_interface values,  memory overflow issue is seen. I have listed the issue seen,
         1. The YDK parser file take the base ietf_interface.py file and our augmented ietf file. It then creates a new ietf_interfaces.py file in "_aug_patch" folder with both base ietf and augmented ietf content. While parsing the comment section, the code hits a logic of end of comment (""") in the generated augmented ietf_interfaces.py file.  Ideally the logic should have ended comment parsing.  But instead the data index is decremented.
                              file:- __init__.py in ietf folder

                              if '"""' in patch_lines[idx]):
                                         idx -=2
                  This was causing the code to access the same index again and again which resulted in the looping. This was causing memory issue.
 
       2. In addition to the looping issue, there was array index out of bound issue.  Because of this issue the ietf_interfaces.py was not properly generated in the ietf/_aug_patch folder. IT was giving IndexError.

**Comment by abhikeshav** [comment]
We welcome contributions. Feel free to open a pull request. See this document for details: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by psykokwak4** [comment]
Sorry, I implemented this, and it should be gone in next version, a temporary work around would be replace [those lines](https://github.com/CiscoDevNet/ydk-gen/blob/209522c0a35681c6307a0e4a999d7a468e64ce41/ydkgen/printer/python/python_bindings_printer.py#L179-L182) with a `pass` statement.

---

This `_aug_patch` folder contains nothing but "patched" model, it assumes:
- The structure of generated `ietf_interfaces.py` and augmented `ietf_interfaces.py` are the same

By structure I mean the nested class structure. And I think the format for comments in generated `ietf_interfaces.py` and your augmented `ietf_interfaces.py` are not the same and the primitive algorithm implemented could not handle comments well. I've thought about using python [`ast`](https://docs.python.org/3.6/library/ast.html) module or something could parse and merge two python classes to handle them in a "smart" way, however it will take too much time to implement.

So in the two issues you mentioned above are actually one issue: the generated `ietf_interfaces.py` and augmented `ietf_interfaces.py` does not have the same structure.

However I think it is better to keep both augmented model and augmentation contributor model in one bundle. For example, creating a profile file contains your augmented ietf file, uninstall `ietf` bundle(assuming you have `ietf` bundle installed), and reinstall this customized bundle. Dependencies such as `openconfig` will be affected after installation, however you could also create a customized profile file for it(example profile file could be found at [here](https://github.com/CiscoDevNet/ydk-gen/blob/4ff06da5432696b82e724efb19a5d3cb5eec8009/profiles/bundles/openconfig_0_1_1.json), and you could "expand" files in [`dependencies`](https://github.com/CiscoDevNet/ydk-gen/blob/4ff06da5432696b82e724efb19a5d3cb5eec8009/profiles/bundles/openconfig_0_1_1.json#L68) under [`models/git`](https://github.com/CiscoDevNet/ydk-gen/blob/4ff06da5432696b82e724efb19a5d3cb5eec8009/profiles/bundles/openconfig_0_1_1.json#L10)).
Let me know if it works for you.

It would be great if could come up with better way to handle it, as Abhi mentioned above we need help for issues like this one. Thanks so much for opening this issue, and sorry about the inconvenience.

**Comment by psykokwak4** [comment]
Closing this issue as clarified in [ydk community discussion](https://communities.cisco.com/thread/79649). The reason for this issue is: code in old Python package generated before 0.5.4 interfere with new Python package generated after 0.5.4.

If you are facing similar issue(index error in `_aug_patch`), please refresh your Python environment. For example, if in your environment, the installed`ietf`, `openconfig`, `cisco-ios-xr` and `custom` are generated using YDK-GEN before 0.5.4:

```bash
$ pip list | grep ydk-models
ydk-models-cisco-ios-xr            6.2.1
ydk-models-ietf                    0.1.1
ydk-models-openconfig              0.1.2
ydk-models-custom                  0.1.2
```
Please uninstall them:
```bash
$ pip uninstall ydk-models-cisco-ios-xr ydk-models-ietf ydk-models-openconfig ydk-models-custom -y
```
Then reinstall standard package through pypi:
```bash
$ pip install ydk-models-ietf
$ pip install ydk-models-openconfig
$ pip install ydk-models-cisco-ios-xr
```
Or regenerate/reinstall them from scratch:
```bash
$ ./generate.py --bundle profiles/bundles/ietf_0_1_1.json
$ ./generate.py --bundle profiles/bundles/openconfig_0_1_2.json
$ ./generate.py --bundle profiles/bundles/cisco-ios-xr_6_2_1.json
$ ./generate.py --bundle custom.json
$ pip install gen-api/python/ietf-bundle/dist/ydk*.gz
$ pip install gen-api/python/openconfig-bundle/dist/ydk*.gz
$ pip install gen-api/python/cisco_ios_xr/dist/ydk*.gz
$ pip install gen-api/python/custom-bundle/dist/ydk*.gz
```
Feel free to post either in [our community](https://communities.cisco.com/community/developer/ydk) or open issues in github if above solution does not apply for you.
