### ISSUE TITLE
having multiprocessing issue with YDKConnection library

### ISSUE THREAD

**Issue by sangmeshcp** [CiscoDevNet/ydk-gen#442]
Im trying to do multiprocessing handling using pool library and looks like YDKConnection doesn't support this multiprocessing to do parallel ydk connections.. 
any test done on this ??

    def method_missing(self,name,*args,**kwargs):
        handle = kwargs.get('handle')
        _handle = self.get_handle(handle)
    
        if name not in dir(self):
>           method = getattr(_handle, name)
E           AttributeError: 'YdkConnection' object has no attribute '__getstate__'

**Comment by psykokwak4** [comment]
Hi Sangamesh,

Where is this `YDKConnection` object comes from? Is it comes from a python package or some python wrapper? Currently, there is no `YDKConnection` in our [code base](https://github.com/CiscoDevNet/ydk-gen/search?utf8=%E2%9C%93&q=YDKConnection&type=).

Or maybe you could share setups for your environment so we could try to reproduce/confirm this issue?
