### ISSUE TITLE
Enum validation not working when a string used

### ISSUE THREAD

**Issue by shgandhi** [CiscoDevNet/ydk-gen#450]
```
entry.encapsulation = xr_ipv4_arp_cfg.ArpEncap.arpa
entry.encapsulation = "arpa"    
entry.entry_type = xr_ipv4_arp_cfg.ArpEntry.static
```
Enum validation not working for a string with valid value as in the snippet above, but throwing type error when invalid string/int values used. 
Tested in 0.5.4 and libydk, issue present in both.
Ref: [http://ydk.cisco.com/py/docs/gen_doc_156b5f09b79ce4fcfe64fdb46542e022c9323041.html#ydk.models.cisco_ios_xr.Cisco_IOS_XR_ipv4_arp_cfg.ArpEncapEnum](url)

**Comment by abhikeshav** [comment]
either of the below are valid since the correct payload is produced. Nothing to be done here :-)
```
entry.encapsulation = xr_ipv4_arp_cfg.ArpEncap.arpa
entry.encapsulation = "arpa"  
```
