### ISSUE TITLE
really fundamental ques!!

### ISSUE THREAD

**Issue by dummyuser1984** [CiscoDevNet/ydk-gen#451]
I am new to networking world... 

1. The model goes into server or client or both??  
2. How do i start a netconf server.. I am working on a virtual func

**Comment by 111pontes** [comment]
The server contains the model file. The client may have it depending on the tools you want to use.  In the case of YDK, you don't need to have to load the model files on the client side.

Regarding your second point, each system has a different setup for the NETCONF/YANG server.  In the case of Cisco IOS XR, this CLI configuration enables the server:
```
netconf-yang agent
 ssh
!
ssh server v2
ssh server netconf vrf default
```

Going forward, please post questions not related to the development of YDK in the community.
https://communities.cisco.com/community/developer/ydk
That will help you get a faster response.  Thanks.
