### ISSUE TITLE
Update docker CI  script to copy cloned yang models and generate fxs

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#46]
Currently, the docker CI script uses pre-generated fxs files. However, the yang files should be used at build time to build fxs files. This will make sure if any changes are made to the test yang files, the changes are pulled in for each travis build

**Comment by abhikeshav** [comment]
On second thought, the meat of the bash script should probably reside on github and be passed to the docker .sh script as an argument. This would make it easier to edit and maintain

**Comment by psykokwak4** [comment]
Agreed, we need to generate fxs files at run time, and passing the test script to docker container
