### ISSUE TITLE
too many dependencies for generated ydk-py?

### ISSUE THREAD

**Issue by einarnn** [CiscoDevNet/ydk-gen#48]
I noticed that these dependencies are in the requirements.txt for ydk-py:

```
Sphinx==1.4a1
sphinx-rtd-theme==0.1.9
XlsxWriter==0.7.3
GitPython==1.0.1
```

These seem like ydk-gen dependencies that should be removed?

**Comment by abhikeshav** [comment]
I agree that these can be removed

**Comment by abhikeshav** [comment]
Fixed in ydk-gen/ydk-py
