### ISSUE TITLE
Testing missing for YDK package installation

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#486]
Installation of `libydk` packages should be tested automatically.  That testing is currently missing and broken packages may be posted accidentally.

 * [x] OSX
 * [x] Ubuntu
 * [x] Centos

**Comment by abhikeshav** [comment]
* [x] OSX
 * [ ] Ubuntu
 * [ ] Centos

Added package installation to `OSX` [test](https://github.com/CiscoDevNet/ydk-py/blob/master/.travis.yml#L13). The ubuntu package does not install well on Travis CI as Travis uses older version of ubuntu (`trusty`). For centos, travis currently does not support this. We may need to look at using docker integration with travis for this task

**Comment by abhikeshav** [comment]
Fixed with https://github.com/CiscoDevNet/ydk-py/pull/32
