### ISSUE TITLE
Interfaces Do not delete on Update

### ISSUE THREAD

**Issue by jbwoo9779** [CiscoDevNet/ydk-gen#495]
It is not entirely clear what I set in xr_ipv4_mfwd_cfg.Mfwd.DefaultContext.Ipv4.Interfaces() to DELETE() (from ydk.types), so that when I call a crud update, it removes that CLI command equivalent. How would I do this?

**Comment by abhikeshav** [comment]
`DELETE` object is meant for deleting leafs. Can you try the below?

```python
interfaces =  xr_ipv4_mfwd_cfg.Mfwd.DefaultContext.Ipv4.Interfaces()
crud.delete(provider, interfaces)
```

**Comment by abhikeshav** [comment]
Feel free to start a discussion on ydk community if you face any issues: https://communities.cisco.com/community/developer/ydk
