### ISSUE TITLE
NetconfService get_config does not support with_defaults option

### ISSUE THREAD

**Issue by sivanandakopperla** [CiscoDevNet/ydk-gen#510]
While using “edit_config” with default_operation like replace and merge, throwing below error.
```python
Pdb) dir(EditConfigRpc.Input.DefaultOperationEnum)
['__class__', '__doc__', '__members__', '__module__', 'merge', 'none', 'replace']
(Pdb) EditConfigRpc.Input.DefaultOperationEnum.merge
<DefaultOperationEnum.merge: 0>
(Pdb) EditConfigRpc.Input.DefaultOperationEnum.replace
<DefaultOperationEnum.replace: 1>
(Pdb) EditConfigRpc.Input.DefaultOperationEnum.none
<DefaultOperationEnum.none: 2>
(Pdb) self.get_mpls_info = self.netconf_service.edit_config(self.provider,Datastore.candidate,self.mpls, default_operation=EditConfigRpc.Input.DefaultOperationEnum.merge)
*** ydk.errors.YPYServiceError: optional arg 'default_operation' must be of type ietf_netconf.EditConfigRpc.Input.DefaultOperationEnum
(Pdb) self.get_mpls_info = self.netconf_service.edit_config(self.provider,Datastore.candidate,self.mpls, default_operation=EditConfigRpc.Input.DefaultOperationEnum.replace)
*** ydk.errors.YPYServiceError: optional arg 'default_operation' must be of type ietf_netconf.EditConfigRpc.Input.DefaultOperationEnum

Observed same error in get_config too.

(Pdb) self.mpls_info = self.netconf_service.get_config(self.provider,Datastore.running,self.mpls, WithDefaultsModeEnum.report_all)
*** ydk.errors.YPYServiceError: optional arg 'with_defaults_option' must be of type ietf_netconf_with_defaults.WithDefaultsModeEnum
```

**Comment by abhikeshav** [comment]
With `ydk 0.6.0` the below works

```python
from ydk.providers import NetconfServiceProvider
from ydk.services import CRUDService
from ydk.types import Datastore
from ydk.services import NetconfService

ncc = NetconfServiceProvider(address=<host-addr> , username='admin', password='admin')
ne = NetconfService()
result=ne.edit_config(ncc,Datastore.candidate,ietf_interfaces.Interfaces(),default_operation= "replace")
```
produces below payload
```
2017-08-04 09:57:59,070 - ydk - INFO - =============Generating payload to send to device=============
2017-08-04 09:57:59,070 - ydk - INFO - <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <target>
    <candidate/>
  </target>
  <default-operation>replace</default-operation>
  <config><interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces"/>
</config>
</edit-config>
</rpc>
```

Currently, `NetconfService.get_config()` does not have `with_defaults` option. It will be added in the next release.

**Comment by sivanandakopperla** [comment]
Hi Abhi,

While installing ydk 0.6.0, got below error.

[nacm_env] [skopperl@bgl-netconf bin]$ pip install ydk==0.6.0
Collecting ydk==0.6.0
  Using cached ydk-0.6.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pybind11>=2.1.1 in /users/skopperl/nacm_env/nacm_env/lib/python3.4/site-packages (from ydk==0.6.0)
Installing collected packages: ydk
  Found existing installation: ydk 0.5.5
    Uninstalling ydk-0.5.5:
      Successfully uninstalled ydk-0.5.5
  Running setup.py install for ydk
    Complete output from command /users/skopperl/nacm_env/nacm_env/bin/python3.4 -c "import setuptools, tokenize;__file__='/tmp/pip-build-m2uglzad/ydk/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-om_934n8-record/install-record.txt --single-version-externally-managed --compile --install-headers /users/skopperl/nacm_env/nacm_env/include/site/python3.4/ydk:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.4
    creating build/lib.linux-x86_64-3.4/ydk
    copying ydk/__init__.py -> build/lib.linux-x86_64-3.4/ydk
    copying ydk/exthook.py -> build/lib.linux-x86_64-3.4/ydk
    creating build/lib.linux-x86_64-3.4/ydk/entity_utils
    copying ydk/entity_utils/__init__.py -> build/lib.linux-x86_64-3.4/ydk/entity_utils
    creating build/lib.linux-x86_64-3.4/ydk/errors
    copying ydk/errors/__init__.py -> build/lib.linux-x86_64-3.4/ydk/errors
    copying ydk/errors/error_handler.py -> build/lib.linux-x86_64-3.4/ydk/errors
    creating build/lib.linux-x86_64-3.4/ydk/ext
    copying ydk/ext/__init__.py -> build/lib.linux-x86_64-3.4/ydk/ext
    creating build/lib.linux-x86_64-3.4/ydk/filters
    copying ydk/filters/__init__.py -> build/lib.linux-x86_64-3.4/ydk/filters
    creating build/lib.linux-x86_64-3.4/ydk/logging
    copying ydk/logging/__init__.py -> build/lib.linux-x86_64-3.4/ydk/logging
    creating build/lib.linux-x86_64-3.4/ydk/models
    copying ydk/models/__init__.py -> build/lib.linux-x86_64-3.4/ydk/models
    creating build/lib.linux-x86_64-3.4/ydk/path
    copying ydk/path/__init__.py -> build/lib.linux-x86_64-3.4/ydk/path
    creating build/lib.linux-x86_64-3.4/ydk/providers
    copying ydk/providers/__init__.py -> build/lib.linux-x86_64-3.4/ydk/providers
    copying ydk/providers/codec_provider.py -> build/lib.linux-x86_64-3.4/ydk/providers
    creating build/lib.linux-x86_64-3.4/ydk/services
    copying ydk/services/__init__.py -> build/lib.linux-x86_64-3.4/ydk/services
    copying ydk/services/codec_service.py -> build/lib.linux-x86_64-3.4/ydk/services
    copying ydk/services/crud_service.py -> build/lib.linux-x86_64-3.4/ydk/services
    copying ydk/services/executor_service.py -> build/lib.linux-x86_64-3.4/ydk/services
    copying ydk/services/netconf_service.py -> build/lib.linux-x86_64-3.4/ydk/services
    creating build/lib.linux-x86_64-3.4/ydk/types
    copying ydk/types/__init__.py -> build/lib.linux-x86_64-3.4/ydk/types
    copying ydk/types/py_types.py -> build/lib.linux-x86_64-3.4/ydk/types
    running build_ext
>>>>>>>>>>>>
    ******CMake Error at CMakeLists.txt:2 (cmake_policy):
      Policy "CMP0048" is not known to this version of CMake.******
 <<<<<<<<<<<<<
    
    CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
    Missing variable is:
    CMAKE_VERSION_COMPILER_ENV_VAR
    CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
    Missing variable is:
    CMAKE_VERSION_COMPILER
    CMake Error: Could not find cmake module file: /tmp/pip-build-m2uglzad/ydk/build/temp.linux-x86_64-3.4/CMakeFiles/2.8.12.2/CMakeVERSIONCompiler.cmake
    CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
    Missing variable is:
    CMAKE_0.5.5_COMPILER_ENV_VAR
    CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
    Missing variable is:
    CMAKE_0.5.5_COMPILER
    CMake Error: Could not find cmake module file: /tmp/pip-build-m2uglzad/ydk/build/temp.linux-x86_64-3.4/CMakeFiles/2.8.12.2/CMake0.5.5Compiler.cmake
    CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
    Missing variable is:
    CMAKE_LANGUAGES_COMPILER_ENV_VAR
    CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
    Missing variable is:
    CMAKE_LANGUAGES_COMPILER
    CMake Error: Could not find cmake module file: /tmp/pip-build-m2uglzad/ydk/build/temp.linux-x86_64-3.4/CMakeFiles/2.8.12.2/CMakeLANGUAGESCompiler.cmake
    -- The C compiler identification is GNU 4.8.5
    -- The CXX compiler identification is GNU 4.8.5
    CMake Error: Could not find cmake module file: CMakeVERSIONInformation.cmake
    CMake Error: Could not find cmake module file: CMake0.5.5Information.cmake
    CMake Error: Could not find cmake module file: CMakeLANGUAGESInformation.cmake
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    CMake Error: CMAKE_VERSION_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_0.5.5_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_LANGUAGES_COMPILER not set, after EnableLanguage
    python library: /usr/local/lib/python3.4/config-3.4m/libpython3.4m.a
    python include: /usr/local/include/python3.4m
    pybind11 include: /users/skopperl/nacm_env/nacm_env/include/site/python3.4;/users/skopperl/nacm_env/nacm_env/include/site/python3.4
    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    ssh_location
        linked by target "ydk_" in directory /tmp/pip-build-m2uglzad/ydk
    ssh_threads_location
        linked by target "ydk_" in directory /tmp/pip-build-m2uglzad/ydk
    ydk_location
        linked by target "ydk_" in directory /tmp/pip-build-m2uglzad/ydk
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-build-m2uglzad/ydk/build/temp.linux-x86_64-3.4/CMakeFiles/CMakeOutput.log".
    /usr/local/lib/python3.4/importlib/_bootstrap.py:321: UserWarning: Module ydk was already imported from None, but /tmp/pip-build-m2uglzad/ydk is being added to sys.path
      return f(*args, **kwds)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-m2uglzad/ydk/setup.py", line 157, in <module>
        zip_safe=False,
      File "/usr/local/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/users/skopperl/nacm_env/nacm_env/lib/python3.4/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.4/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/local/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-m2uglzad/ydk/setup.py", line 69, in run
        self.build_extension(ext)
      File "/tmp/pip-build-m2uglzad/ydk/setup.py", line 93, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp)
      File "/usr/local/lib/python3.4/subprocess.py", line 561, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-build-m2uglzad/ydk', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-build-m2uglzad/ydk/build/lib.linux-x86_64-3.4', '-DPYBIND11_INCLUDE=/users/skopperl/nacm_env/nacm_env/include/site/python3.4;/users/skopperl/nacm_env/nacm_env/include/site/python3.4', '-DPYTHON_LIBRARY=/usr/local/lib/python3.4/config-3.4m/libpython3.4m.a', '-DPYTHON_INCLUDE=/usr/local/include/python3.4m', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1
    
    ----------------------------------------
  Rolling back uninstall of ydk

**Comment by psykokwak4** [comment]
Saw this error before when I used CMAKE==2.8, solved it using newer version of CMAKE. You might also need to install libydk before ydk python library.

**Comment by sivanandakopperla** [comment]
I installed cmake3 then i got below error

    pybind11 include: /users/skopperl/cafy_env/include/site/python3.6;/users/skopperl/cafy_env/include/site/python3.6
    **CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    ydk_location
        linked by target "ydk_" in directory /tmp/pip-build-iaxfj3h8/ydk
    
    -- Configuring incomplete, errors occurred!**
    See also "/tmp/pip-build-iaxfj3h8/ydk/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):

**Comment by abhikeshav** [comment]
The error indicates the libydk is not installed. Do you have the system requirements installed as mentioned [here](https://github.com/CiscoDevNet/ydk-py#system-requirements)?

**Comment by 111pontes** [comment]
@sivanandakopperla, were you able to complete your installation?  Let us know if the issue persists with the latest version. Thanks.

**Comment by sivanandakopperla** [comment]
Thanks Abhi. Default operations are working in ydk6

**Comment by ygorelik** [comment]
Not applicable to 0.8.4.
