### ISSUE TITLE
Segmentation fault with Platform model for Crud Service Create operation - YDK-0.6.0

### ISSUE THREAD

**Issue by Prasadmanvish** [CiscoDevNet/ydk-gen#527]
- Segmentation fault with Platform model for Crud Service Create operation. The Segmentation fault is observed only on YDK-0.6.0. Find the screenshot attached for more information
![segmentation_fault](https://user-images.githubusercontent.com/31431538/29807694-b0f8e6b0-8cb2-11e7-9e21-9dddcb666da7.jpg)

**Setup Details**:
Router: XRV9k
YDK Version : 0.6.0
Python Version : 2.7

**Configured nodes for Platform**:

component.name = "optical_channel"
component.optical_channel.config.frequency = 1000
component.optical_channel.config.line_port = "optlineone"
component.optical_channel.config.operational_mode = 100

The same operation is working on YDK-0.5.5. Find the successful logs attached for YDK-0.5.5

**Comment by abhikeshav** [comment]
This issue is caused because a deviation (`cisco-ios-xr-openconfig-platform-deviations.yang`) is active on the device. It acts upon an augmented node. Because of this, the augmented child pointer coming from libyang is `NULL`. Just needed to check for this case
