### ISSUE TITLE
Identity classes in YDK-Py and YDK-Cpp do not use CapWords

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#538]
The naming of identity classes doesn follow CapWords in YDK-Py 0.6.0.  For instance:
http://ydk.cisco.com/py/docs/gen_doc_8afdd1da8f494fd1f80e8849f77bfb6034464cee.html
http://ydk.cisco.com/cpp/docs/gen_doc_8afdd1da8f494fd1f80e8849f77bfb6034464cee.html

**Comment by ylil93** [comment]
The current openconfig bundle that is publicly available via pip is outputting "AddPathsIdentity" for that class. However the documentation generated from source code on the master branch is outputting "ADD_PATHS". I can correct output be "AddPaths"
