### ISSUE TITLE
Invalid Input error exception thrown for MasterKeyAdd. Input()

### ISSUE THREAD

**Issue by Prasadmanvish** [CiscoDevNet/ydk-gen#545]
![input_error_execution_screenshot](https://user-images.githubusercontent.com/31431538/30308600-19fd0dca-97a4-11e7-8f77-13786f0f1eb1.jpg)
Description:

Invalid input error thrown MasterKeyAdd.Input() object is passed has parameter in crud_create operation

Steps To Reproduce:

- Create a MasterKeyAdd.Input() object
- Assign value to new_key leaf
- Pass the object has parameter in crud_create 

YDK throws error. Find the attached screenshot for more information.

Also find the attached logs for test execution

Script Details:

masterkey_add = MasterKeyAdd.Input()
        masterkey_add.new_key = "<key>"
![input_error_execution_screenshot](https://user-images.githubusercontent.com/31431538/30308780-2ff88f9a-97a5-11e7-9e2d-d955da875725.jpg)

        crud_service.create(provider, masterkey_add)

**Comment by psykokwak4** [comment]
If the `MasterKeyAdd` comes from `Cisco_IOS_XR_lib_keychain_act` module, then executor service might be a better choice than crud service:

```python
import logging
logger = logging.getLogger("ydk")
logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler()
formatter = logging.Formatter(("%(asctime)s - %(name)s - "
                              "%(levelname)s - %(message)s"))
handler.setFormatter(formatter)
logger.addHandler(handler)

from ydk.services import ExecutorService
from ydk.providers import NetconfServiceProvider
from ydk.models.cisco_ios_xr import Cisco_IOS_XR_lib_keychain_act as xr_keychain_act

provider = NetconfServiceProvider("127.0.0.1","admin","admin")
executor = ExecutorService()

masterkey_rpc = xr_keychain_act.MasterKeyAdd()  # create object
masterkey_rpc.input.new_key = ""

executor.execute_rpc(provider, masterkey_rpc)
```

similar issue #546

**Comment by 111pontes** [comment]
See closing comments for issue #546 for further help.  Closing as issue seems the result of invoking hte wrong service.
