### ISSUE TITLE
Invalid Input error exception thrown for Logmsg. Input()

### ISSUE THREAD

**Issue by madhukak** [CiscoDevNet/ydk-gen#546]
In Cisco_IOS_XR_syslog_act module

Invalid input error thrown Logmsg.Input() object is passed has parameter in crud_create operation

Steps To Reproduce:

Create a Logmsg.Input() object
Assign value to new_key leaf
Pass the object has parameter in crud_create
YDK throws error. Find the attached screenshot for more information.

Also find the attached logs for test execution

Script Details:

       inpt = logmsg.Input()
       inpt.message = "Critical"
       inpt.severity = 2
       logmsg.input = inpt
![input_error](https://user-images.githubusercontent.com/31876482/30310150-9ef07d8e-97ac-11e7-824d-b3e83048784e.png)

**Comment by psykokwak4** [comment]
The `Logmsg` is an `rpc` instance, maybe executor service is better choice than crud:

```python
import logging
logger = logging.getLogger("ydk")
logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler()
formatter = logging.Formatter(("%(asctime)s - %(name)s - "
                              "%(levelname)s - %(message)s"))
handler.setFormatter(formatter)
logger.addHandler(handler)

from ydk.services import ExecutorService
from ydk.providers import NetconfServiceProvider
from ydk.models.cisco_ios_xr import Cisco_IOS_XR_syslog_act as xr_syslog_act
from ydk.models.ietf import ietf_syslog_types

def prepare_logmsg_rpc(logmsg_rpc):
    """Add RPC input data to logmsg_rpc object."""
    logmsg_rpc.input.message = "A custom informational message"
    logmsg_rpc.input.severity = ietf_syslog_types.Severity.info

provider = NetconfServiceProvider("127.0.0.1","admin","admin")
executor = ExecutorService()

logmsg_rpc = xr_syslog_act.Logmsg()  # create object
prepare_logmsg_rpc(logmsg_rpc)  # add RPC input

executor.execute_rpc(provider, logmsg_rpc)
```

More syslog samples could be found [here](https://github.com/CiscoDevNet/ydk-py-samples/tree/650ff38ddac3c2a410e50df6d12e0a3e8af73321/samples/basic/executor/models/cisco-ios-xr/Cisco-IOS-XR-syslog-act). (Please remove `Rpc` suffix for 0.6.0 compatibility, so `LogmsgRpc` --> `Logmsg`).

**Comment by madhukak** [comment]
Hi,

Thanks for your inputs.

I can successfully do the create/update  operation with “execute”.

I am unable to do the read operation for the configured entities with “execute” services as in CRUD services.

Is there any way that I can do read operation  with execute services ?



Thanks
Madhukar

**Comment by abhikeshav** [comment]
Hi Madhukar,

You can use the `CRUDService` for doing `read` operation.

**Comment by madhukak** [comment]
Hi Abhi,


I tried with following (CRUDService for read operation)

CODE:
    def read_xr_syslog_act(self,crud_service,provider):
        logmsg_rpc = xr_syslog_act.Logmsg()  # create object
        #pdb.set_trace()
        crud_service.read(provider,logmsg_rpc)
        logging.info(logmsg_rpc.input.message)



    def test_xr_syslog_act_read(self):
        print("TestSyslogAct : test_xr_syslog_act_read")
        syslogobj = XR_SyslogAct()
        syslogobj.read_xr_syslog_act(crud_service,provider)



And I am getting fatal error:

--------------------------------------------------- generated html file: /auto/ng_ott_auto/DEVELOPMENT_USERS/madhukak/Tests/syslog_report.html ----------------------------------------------------
============================================================================================ FAILURES =============================================================================================
______________________________________________________________________________ TestSyslogAct.test_xr_syslog_act_read ______________________________________________________________________________

self = <xr_lib_syslog_act.TestSyslogAct object at 0x2ac96cada210>

    def test_xr_syslog_act_read(self):
        print("TestSyslogAct : test_xr_syslog_act_read")
        syslogobj = XR_SyslogAct()
>       syslogobj.read_xr_syslog_act(crud_service,provider)

xr_lib_syslog_act.py:72:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../Traversal/xr_syslog_act.py:45: in read_xr_syslog_act
    crud_service.read(provider,logmsg_rpc)
/usr/local/lib/python2.7/site-packages/ydk/errors/error_handler.py:112: in helper
    return func(self, provider, entity, *args, **kwargs)
/usr/local/lib/python2.7/site-packages/ydk/services/crud_service.py:35: in read
    return self._crud.read(provider, read_filter)
/usr/local/lib/python2.7/contextlib.py:35: in __exit__
   self.gen.throw(type, value, traceback)
/usr/local/lib/python2.7/site-packages/ydk/errors/error_handler.py:82: in handle_runtime_error
    _raise(_exc)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

exc =  <?xml version="1.0"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1...ternal manageability-engine error'</error-message>
  </rpc-error>
</rpc-reply>


    def _raise(exc):
        """Suppress old exception context for Python > 3.3,
        Use exec to avoid SyntaxError under Python 2 environment.
        """
        if sys.version_info >= (3,3):
            exec("raise exc from None")
        else:
>           raise exc
E           YPYServiceProviderError:  <?xml version="1.0"?>
E           <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
E             <rpc-error>
E               <error-type>application</error-type>
E               <error-tag>operation-failed</error-tag>
E               <error-severity>error</error-severity>
E               <error-path xmlns:ns1="http://cisco.com/ns/yang/Cisco-IOS-XR-syslog-act">ns1:logmsg</error-path>
E               <error-message xml:lang="en">'YANG framework' detected the 'fatal' condition 'Internal manageability-engine error'</error-message>
E             </rpc-error>
E           </rpc-reply>

/usr/local/lib/python2.7/site-packages/ydk/errors/error_handler.py:56: YPYServiceProviderError
=============================================================================== 1 failed, 1 passed in 30.45 seconds ===============================================================================
-

**Comment by abhikeshav** [comment]
Hi Madhukar,



This is an error coming from the device. Can you please send an email to the appropriate component team with the full XML logs? Also include yang-dk mailer.



Thanks,

Abhi

**Comment by 111pontes** [comment]
You can't invoke the CRUD service on an RPC model.  Note that a YANG model may define config/oper data and RPCs.  The model you're using defines an RPC (no config/oper data).  You may want to read this [XR Data-model Overview](https://xrdocs.github.io/programmability/tutorials/2016-09-15-xr-data-model-overview/).  If you're trying to invoke the Syslog RPC defined in [Cisco-IOS-XR-syslog-act](https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/622/Cisco-IOS-XR-syslog-act.yang), you need to make use of the [Executor service](http://ydk.cisco.com/py/docs/api/services/executor_service.html) in YDK instead. You can find multiple examples in the [ydk-py-samples](https://github.com/CiscoDevNet/ydk-py-samples/tree/master/samples/basic/executor/models/cisco-ios-xr/Cisco-IOS-XR-syslog-act) repository.  If you need further assistance with that model or the service, I'd suggest you post the question in the [YDK community](https://communities.cisco.com/community/developer/ydk).  If you identify a probelm in YDK that needs fixing, we can certainly reopen this issue.  Thanks.
