### ISSUE TITLE
OC-Model statsd: RPC generation is  inconsistency

### ISSUE THREAD

**Issue by vinogovi** [CiscoDevNet/ydk-gen#547]
Description: OC-Model statsd: RPC generation is inconsistency ,while configuring the node "ServiceAccounting" under component statsd. PRC generation is inconsistency. 
1. First time while configuring Service accounting polling_period , RPC generated and the configuration was successful.
2. was able to do create, read and update configuration 3. Now the same node , failed to generate the RPC.

Note: verified in Fretta --> Version      : 6.4.1.11I
  and skywarp platform --> Version      : 6.3.2.07I

[stats_trace.txt](https://github.com/CiscoDevNet/ydk-gen/files/1295605/stats_trace.txt)

**Comment by abhikeshav** [comment]
I don't understand the issue. Please clarify the above as it is hard to make out what the problem is

**Comment by vinogovi** [comment]
Hi Abhi,

I trying to create crud service and able to generate RPC , But not able to find the any attribute value in the RPC send payload. 
Also got RPC reply as OK, when checked show running config nothing was configured. 

RPC payload: 
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:b6c2fb27-2c11-4bf5-896f-4f7aba19d68b">
  <edit-config>
    <target>
      <candidate/>
    </target>
    <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
      <statistics xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-infra-statsd-cfg"/>
    </config>
  </edit-config>
</rpc>


<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:b6c2fb27-2c11-4bf5-896f-4f7aba19d68b">
  <ok/>
</rpc-reply>


<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <commit/>
</rpc>


<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:b6c2fb27-2c11-4bf5-896f-4f7aba19d68b">
  <ok/>
</rpc-reply>

CREATE operation completed

Code snip : 
from ydk.models.cisco_ios_xr import Cisco_IOS_XR_infra_statsd_cfg

 def Service_Accounting_config(self):
       ab = Cisco_IOS_XR_infra_statsd_cfg.Statistics()
       pdb.set_trace()
       ob = ab.Period.ServiceAccounting()
       ob.polling_period = 90
       self.crudservice.create(self.provider, ab)

**Comment by vinogovi** [comment]
Hi Abhi,

·         While configuring the container “ServiceAccounting” in the component   “Cisco_IOS_XR_infra_statsd_cfg” RPC is getting generated without any leaf values passed. But  getting RPC reply as OK.
CREATE operation initiated
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:b6c2fb27-2c11-4bf5-896f-4f7aba19d68b">
  <edit-config>
    <target>
      <candidate/>
    </target>
    <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
      <statistics xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-infra-statsd-cfg"/>
    </config>
  </edit-config>
</rpc>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:b6c2fb27-2c11-4bf5-896f-4f7aba19d68b">
  <ok/>
</rpc-reply>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <commit/>
</rpc>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:b6c2fb27-2c11-4bf5-896f-4f7aba19d68b">
  <ok/>
</rpc-reply>

CREATE operation completed
Code snip :
from ydk.models.cisco_ios_xr import Cisco_IOS_XR_infra_statsd_cfg
def Service_Accounting_config(self):
       ab = Cisco_IOS_XR_infra_statsd_cfg.Statistics()
       pdb.set_trace()
       ob = ab.Period.ServiceAccounting()
       ob.polling_period = 90
       self.crudservice.create(self.provider, ab)


Regards,
Vinoth G.

**Comment by abhikeshav** [comment]
Thanks. Formatted your post a bit

**Comment by abhikeshav** [comment]
Try the below. It is working for me:
```python
from ydk.models.cisco_ios_xr import Cisco_IOS_XR_infra_statsd_cfg
def Service_Accounting_config(self):
       ab = Cisco_IOS_XR_infra_statsd_cfg.Statistics()
       ab.period.service_accounting.polling_period = 90
       self.crudservice.create(self.provider, ab)
```

**Comment by vinogovi** [comment]
Hi Abhi,

Thank you . Now able to generate the RPC Payload.

Regards,
Vinoth G.

**Comment by abhikeshav** [comment]
Glad it worked
