### ISSUE TITLE
 Cisco_IOS_XR_infra_infra_clock_cfg: NOt able to create object for Enam class

### ISSUE THREAD

**Issue by vinogovi** [CiscoDevNet/ydk-gen#548]
Not able to create the object for Enum classes : ClockMonth and ClockSummerTimeMode
getting errror as "'module' object has no attribute 'ClockMonth'"

not able to assign the enum values to the leafs" mode", "start_month" under the nodes "Summertime " and "TimeZone"
 
Code snip from the debugger:

(Pdb) from ydk.models.cisco_ios_xr import Cisco_IOS_XR_infra_infra_clock_cfg as cl
(Pdb) aa = cl.Clock()
(Pdb) ab = cl.ClockMonth()
*** AttributeError: 'module' object has no attribute 'ClockMonth'
(Pdb)

**Comment by psykokwak4** [comment]
`ClockMonth` is generated as `ClockMonthEnum`) in [0.5.5](https://github.com/CiscoDevNet/ydk-py/blob/db2feddee1d91c992fe1c6ac154133504b33d0fb/cisco-ios-xr/ydk/models/cisco_ios_xr/Cisco_IOS_XR_infra_infra_clock_cfg.py#L27). Not able to reproduce using 0.6.0:
```python
In [1]: from ydk.models.cisco_ios_xr import Cisco_IOS_XR_infra_infra_clock_cfg as cl

In [2]: aaa = cl.ClockMonth()

In [3]: aaa
Out[3]: <ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_infra_clock_cfg.ClockMonth at 0x107fa3780>

In [4]: bbb = cl.Clock()

In [5]: bbb
Out[5]: <ydk.models.cisco_ios_xr.Cisco_IOS_XR_infra_infra_clock_cfg.Clock at 0x107fa36d0>
```

[backward compatibility notes](http://ydk.cisco.com/py/docs/guides/backward_compatibility.html#api-changes)

**Comment by abhikeshav** [comment]
try something like the below referring to the (http://ydk.cisco.com/py/docs/gen_doc_f6da6d7be28cbdaa1aa689fd29bb44fca419b23b.html)[documentation]:
```python
from ydk.models.cisco_ios_xr import Cisco_IOS_XR_infra_infra_clock_cfg as cl

clock = cl.Clock()
clock.summer_time = cl.Clock.SummerTime() # need to initialize since it is a presence container
clock.summer_time.mode = cl.ClockSummerTimeMode.recurring
```

**Comment by vinogovi** [comment]
I have changed the code as per your suggestion , still facing the same issue.

(Pdb) clock.summer_time = cl.Clock.SummerTime()
(Pdb) clock.summer_time.mode = cl.ClockSummerTimeMode.recurring
*** AttributeError: 'module' object has no attribute 'ClockSummerTimeMode'
(Pdb) clock.summer_time.time_zone_name = "IST"
(Pdb)

**Comment by psykokwak4** [comment]
Can you try `cl.ClockEnum`? Seems like you are using YDK < 0.6.0

**Comment by abhikeshav** [comment]
@vinogovi Let me know if this issue is resolved

**Comment by abhikeshav** [comment]
Let me know if this is still an issue and will reopen
