### ISSUE TITLE
Open Config-Terminal Devices: Unable to configure Logical Channels in terminal Device

### ISSUE THREAD

**Issue by vinogovi** [CiscoDevNet/ydk-gen#552]
While trying to configure Logical channel in Terminal devices 
1. RPC payload failed to take the values for "logical_channel_type", "rate_class", "trib_protocol".
2. while trying through CLI getting below error.
```ssh
"RP/0/RP0/CPU0:ios(config-logical-channel)#logical-channel-type ethernet 
 Failed to commit one or more configuration items during a pseudo-atomic operation. All changes made have been reverted. Please issue 'show configuration failed [inheritance]' from this session to view the errors"
```

Code snip:

```python
from ydk.models.openconfig import openconfig_terminal_device as td
def logical_channels_config(self):
       ab = td.TerminalDevice()
#       ac = ty.LoopbackModeType()
       lc =ab.LogicalChannels.Channel()
       lc.index = 1
       lc.config.index = lc.index
       lc.index = lc.config.index
       lc.config.description = "configuring logical channel"
#       lc.config.admin_state = 
#       lc.config.loopback_mode = none
       lc.config.logical_channel_type = "Ethernet"
       lc.config.rate_class = "10G"
#       lc.config.trib_protocol = "Prot_10Ge_WanIdentity"
       ab.logical_channels.channel.append(lc)
       pdb.set_trace()
       self.crudservice.create(self.provider, ab)
```
[TD_RPC.txt](https://github.com/CiscoDevNet/ydk-gen/files/1305656/TD_RPC.txt)

**Comment by abhikeshav** [comment]
Formatted your post a bit

**Comment by 111pontes** [comment]
@vinogovi, you're not really running into a YDK issue here.  The optical device is rejecting your configuration.  Most likely, your configuration is incomplete.  I'd suggest you post your question in the [YDK community](https://communities.cisco.com/community/developer/ydk) where other users may be able to provide assistance.  If you can confirm that a change is needed in YDK, we'd gladly re-open this issue.  I'll close for now.
