### ISSUE TITLE
ydk-ansible module

### ISSUE THREAD

**Issue by jabelk** [CiscoDevNet/ydk-gen#555]
Any plans to make a ydk ansible module, like there is for napalm and networktocode?
ex:
https://github.com/napalm-automation/napalm-ansible
https://github.com/networktocode/ntc-ansible

**Comment by 111pontes** [comment]
YDK is being used actively to develop Ansible modules.  YDK represents a much higher level of abstraction on device management.  You should expect those modules being more focused on workflows and less on protocols, encodings, etc.  The latter tend to be exposed in the initial efforts to bring network automation to Ansible.  You can find a simple example of a module to verify IP reachability at:
https://github.com/111pontes/xr-pl2/tree/master/ansible/ip_destination_reachable

On a side note, please post future questions to the [YDK community](https://communities.cisco.com/community/developer/ydk).  You'll reach a much larger audience. Thanks.
