### ISSUE TITLE
Ipv4 traceroute response is NULL

### ISSUE THREAD

**Issue by sabommen** [CiscoDevNet/ydk-gen#558]
Trying to automate "Cisco_IOS_XR_traceroute_act" module. Rpc  payload for sending to device is getting generated properly , but not getting ipv4 traceroute response and error is also not thrown for ipv4. Getting only ipv6 response though have not configured for ipv6.

```ssh
=============Generating payload to send to device=============
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><traceroute xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-traceroute-act">
  <destination/>
  <ipv4>
    <destination>192.168.122.1</destination>
    <source>192.168.122.170</source>
    <timeout>3</timeout>
    <probe>3</probe>
    <numeric>false</numeric>
    <vrf-name>default</vrf-name>
    <min-ttl>1</min-ttl>
    <max-ttl>30</max-ttl>
    <port>22</port>
    <verbose>true</verbose>
  </ipv4>
  <ipv6/>
</traceroute>
</rpc>
```

If trying to configure "destination" container , getting "bad hostname or protocol not running " error for correct configurations also.

Logs are attached.

[traceroute_log.txt](https://github.com/CiscoDevNet/ydk-gen/files/1313866/traceroute_log.txt)

**Comment by abhikeshav** [comment]
Thanks. Formatted your post

**Comment by abhikeshav** [comment]
For such issues which are coming from the XR device side, can you please send an email the component team and yang-dk mailer?

**Comment by abhikeshav** [comment]
Sorry. My above comment is wrong. This is a duplicate of #558, which is now closed
