### ISSUE TITLE
Latest xrv sunstone image is not packaged with lates Cisco-IOS-XR-aaa-locald-admin-cfg.yang 

### ISSUE THREAD

**Issue by sabommen** [CiscoDevNet/ydk-gen#559]
Router is running with below image . 
Cisco-IOS-XR-aaa-locald-admin-cfg.yang file on router is different than the one which is present in latest ydk models. 
Difference is leaf “secret” is of type ‘string’ in wiki(latest ydk package) but it of type ‘container’ on router.
Because of this difference  getting “Yang framework violation” error when  trying to configure username.

```ssh
Build Information:
Built By     : svustipa
Built On     : Thu Sep  7 03:29:11 PDT 2017
Build Host   : iox-ucs-012
Workspace    : /auto/iox-ucs-012-san2/production/6.4.1.13I.DT_IMAGE/xrv9k/workspace
Version      : 6.4.1.13I
Location     : /opt/cisco/XR/packages/

cisco IOS-XRv 9000 () processor 
System uptime is 2 hours, 11 minutes
```

**Comment by abhikeshav** [comment]
For such issues which are coming from the XR device side, can you please send an email the component team and yang-dk mailer?
