### ISSUE TITLE
Cisco-IOS-XR Traffic-Collector: Mandatory key is not set for feature enable in YDK API 

### ISSUE THREAD

**Issue by Anbuvelu** [CiscoDevNet/ydk-gen#560]
Hi,
when I try to do CRUD create for Traffic Collector with all the mandatory keys mentioned in YDK API, unable to Create a TC according to values set in API, had raised this issue to components team, and it is expected the feature to be enabled on the global level to do create, but while doing manually using cli, there is no explicit command to enable globally,

So it would be better to update the "Cisco_IOS_XR_infra_tc_cfg module" YDK wiki with enable on the global and interface levels as mandatory parameters.

PFB the YDK wiki for Traffic collector,

http://ydk.cisco.com/py/docs/gen_doc_75c725fd4621852a5a89ff82c90518d110cb9d6c.html 

[Re Regarding- CSCvf92539-Traffic Collector configs are not getting configured for XRv 9K device using YDK-0.6.0.msg.zip](https://github.com/CiscoDevNet/ydk-gen/files/1316646/Re.Regarding-.CSCvf92539-Traffic.Collector.configs.are.not.getting.configured.for.XRv.9K.device.using.YDK-0.6.0.msg.zip)

**Comment by abhikeshav** [comment]
The YDK documentation and python code is autogenerated from the Cisco-IOS-XR yang model. Yang model is found [here](https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/622/Cisco-IOS-XR-infra-tc-cfg.yang). The model is still owned by component team. Can you ask them to update the model?
