### ISSUE TITLE
List encoding is performed in a fixed order

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#563]
in YDK 0.6.0, the ordering of list items is not preserved when data is encoded.  Maintaining list ordering is particularly important for those lists that can be ordered by user according to the YANG model.  However, maintaining ordering should happen even for lists "ordered by system" to provide ease of use/debugging for the developer.  Somewhat related to issue #564.

**Comment by abhikeshav** [comment]
Fixed in #586
