### ISSUE TITLE
Cisco_IOS_XR_policy_repository_cfg: RPC getting generated successfully but failed to configure in device

### ISSUE THREAD

**Issue by vinogovi** [CiscoDevNet/ydk-gen#568]
Hi 
1. RPC getting generated successfully with the values passed , but the failed to configure the device.
2. Same attributes I tried configure via CLI but I don't see the attributes same as YDK.

Code snip:

from ydk.models.cisco_ios_xr import Cisco_IOS_XR_policy_repository_cfg
ab = Cisco_IOS_XR_policy_repository_cfg.RoutingPolicy()
        ab.limits.maximum_lines_of_policy = 131075
        ab.limits.maximum_number_of_policies = 6000
        ab.editor = "vim"
        ac = ab.RoutePolicies.RoutePolicy()
        ac.route_policy_name = "test1"
        ac.rpl_route_policy = "route policy"
        ab.route_policies.route_policy.append(ac)
        ad = ab.Sets.AppendEsiSets.AppendEsiSet()
        ad.set_name = "sample"
        ad.esi_set_as_text = "sample test policy"
        ab.sets.append_esi_sets.append_esi_set.append(ad)
        self.crudservice.create(self.provider, ab)

Please let me know how to proceed further.
Regards,
Vinoth G.
[policy_repo.txt](https://github.com/CiscoDevNet/ydk-gen/files/1324019/policy_repo.txt)

**Comment by abhikeshav** [comment]
Can you please send the XML logs to the component team? Feel free to CC the ydk mailer

**Comment by abhikeshav** [comment]
Closing as this is a device-side issue
