### ISSUE TITLE
YDK upgrade 0.6.0 in ubuntu(debian) fails because of libydk incompatibility

### ISSUE THREAD

**Issue by mjegathe** [CiscoDevNet/ydk-gen#569]
We have a 32-bit x86 running a Ubuntu (Debian).
Execution server has following details:
root@frettay:/home/mubhatta# uname -a
Linux frettay 3.13.0-88-generic #135-Ubuntu SMP Wed Jun 8 21:10:37 UTC 2016 i686 i686 i686 GNU/Linux

Prerequsite for installing ydk0.6 is to have libydk installed.  We either have libydk compiled for x86 (rpm) or amd (debian). We do not have x86 (debian) libydk.
Source: http://ydk.cisco.com/py/docs/getting_started.html

**Comment by abhikeshav** [comment]
Please find the i386 libydk image here: https://devhub.cisco.com/artifactory/webapp/#/artifacts/browse/tree/General/debian-ydk/0.6.0/libydk_0.6.0-1_i386.deb
