### ISSUE TITLE
Iteration Container Unavailable in module cisco_ios_xr_man_xml_ttyagent_cfg in XrXML->Agent->Default

### ISSUE THREAD

**Issue by rayyanar** [CiscoDevNet/ydk-gen#572]
For the YDK Module cisco_ios_xr_man_xml_ttyagent_cfg we see the following behaviour.
1. In order to set the value of streaming_size inside XrXML --> Agent -->Default --> Iteration needs to be turned off.
2. We don't have a Container "Iteration" inside the Default Container.

Please find the pdb output at two levels.

**(Pdb) dir(**obj_xrxml.agent.default**)**
['Session', 'Throttle', 'Vrfs', '__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_check_monkey_patching_error', '_children_name_map', '_children_yang_names', '_get_child_by_seg_name', '_local_refs', '_prefix', '_revision', 'clone_ptr', 'enable', 'get_child_by_name', 'get_children', 'get_entity_path', 'get_segment_path', 'has_data', 'has_leaf_or_child_of_name', 'has_operation', 'ipv4_disable', 'ipv6_enable', 'is_presence_container', 'iteration_size', 'parent', 'session', 'set_filter', 'set_value', 'streaming_size', 'throttle', 'vrfs', 'yang_name', 'yang_parent_name', 'yfilter']

**(Pdb) dir(obj_xrxml.Agent.Default)**
['Session', 'Throttle', 'Vrfs', '__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_check_monkey_patching_error', '_get_child_by_seg_name', '_prefix', '_revision', 'clone_ptr', 'get_child_by_name', 'get_children', 'get_entity_path', 'get_segment_path', 'has_data', 'has_leaf_or_child_of_name', 'has_operation', 'is_presence_container', 'parent', 'set_filter', 'set_value', 'yang_name', 'yang_parent_name', 'yfilter']
(Pdb)

**Comment by abhikeshav** [comment]
Can you please
 *  post your script and
 * enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs?

**Comment by rayyanar** [comment]
Hi Abhi, 

This issue is currently not reproducible on the XRv9K Image version 6.4.1.13I.  Yesterday when we raised this  the XRv9K was running the Image version 6.3.1.28I.  Sorry about it.

Thanks,
Ramkumar
