### ISSUE TITLE
"Invalid path: openconfig-terminal-device:optical-channel" error with YDK-0.6.1

### ISSUE THREAD

**Issue by Prasadmanvish** [CiscoDevNet/ydk-gen#591]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.
Invalid path: openconfig-terminal-device:optical-channel error with YDK-0.6.1
## Expected Behavior
YDK 0.6.1 should configure Optical channel with below values

 component = Components.Component()
 component.name = "0/0-OpticalChannel0/0/0/19"
 component.optical_channel.config.frequency = 191600000
 component.optical_channel.config.line_port = "0/0-Optics0/0/0/19"
 component.optical_channel.config.operational_mode = 2
 component.optical_channel.config.target_output_power = 100
 crud_service.create(provider, component)

## Current Behavior
YDK-0.6.1 is throwing errors. Find the attached log file for more information

Note: Same code used to give RPC OK message with YDK-0.5.5

## Steps to Reproduce
Configure the Optical channel with below mentioned values

component = Components.Component()
 component.name = "0/0-OpticalChannel0/0/0/19"
 component.optical_channel.config.frequency = 191600000
 component.optical_channel.config.line_port = "0/0-Optics0/0/0/19"
 component.optical_channel.config.operational_mode = 2
 component.optical_channel.config.target_output_power = 100
 crud_service.create(provider, component)

Create operation fails with the error message

## Your Script

```
component = Components.Component()
 component.name = "0/0-OpticalChannel0/0/0/19"
 component.optical_channel.config.frequency = 191600000
 component.optical_channel.config.line_port = "0/0-Optics0/0/0/19"
 component.optical_channel.config.operational_mode = 2
 component.optical_channel.config.target_output_power = 100
 crud_service.create(provider, component)


```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```
Logs attached in file
```

## System Information

Python Version 2.7
Router Tested:XRV9k VXR, NCS1K
Route Operating System: CISCO-IOS-XR
Client Operating System: CENTOS7
[Test_Openconfig_Platform.log](https://github.com/CiscoDevNet/ydk-gen/files/1361704/Test_Openconfig_Platform.log)
![oc_platform_screenshot](https://user-images.githubusercontent.com/31431538/31265605-5955b534-aa8d-11e7-866b-253fb6df793a.jpg)

**Comment by ygorelik** [comment]
The issue appears to be in the IOS XR image, which is missing reference of Yang module openconfig-terminal-device.yang in the device capabilities. See attached console output for complete details.

Important to note that the model file openconfig-terminal-device.yang is present in the yang directory.

[Issue_591__Device_capabilities.txt](https://github.com/CiscoDevNet/ydk-gen/files/1691166/Issue_591__Device_capabilities.txt)

YDK test file:
[test.zip](https://github.com/CiscoDevNet/ydk-gen/files/1691175/test.zip)

**Comment by abhikeshav** [comment]
This should be fixed on device side. Communicated to relevant team
