### ISSUE TITLE
Cisco-IOS-XR-ipv4-smiap-cfg module: Error "mandatory leaf missing from request" but configuration of leaf is given

### ISSUE THREAD

**Issue by kirti502781** [CiscoDevNet/ydk-gen#596]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
Configurations for IPv4 virtual address for management interfaces should reply with ok

## Current Behavior
No ok in reply received from device. (RPC reply as mandatory leaf missing from request)

## Steps to Reproduce
1. Configure the  IPv4 virtual address for management interfaces.
2. Received RPC error as "mandatory leaf missing from request"

## Your Script
```python
        obj_smiap = ipv4_smiap_cfg.Ipv4Virtual()
        obj_smiap.use_as_source_address = Empty()
        obj_vrf = obj_smiap.Vrfs.Vrf() 
        obj_vrf.vrf_name = "default"
        pdb.set_trace()
        obj_address = obj_vrf.Address()
        obj_vrf.address = obj_address
        obj_address.address = "192.168.10.23/8"
        obj_address.netmask = 24
        obj_smiap.vrfs.vrf.append(obj_vrf)
        crud_service.create(provider, obj_smiap)
```

## Logs
```
ydk.errors.YPYServiceProviderError:  <?xml version="1.0"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>missing-element</error-tag>
    <error-severity>error</error-severity>
    <error-path xmlns:ns1="http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-smiap-cfg">ns1:ipv4-virtual/ns1:vrfs/ns1:vrf[vrf-name = 'default']/ns1:address/ns1:address</error-path>
    <error-info>
      <bad-element>address</bad-element>
      <error-message>mandatory leaf missing from request, please add it and try again.</error-message>
    </error-info>
  </rpc-error>
</rpc-reply>
```
Full logs are attached in file: ipv4_smiap.log

## System Information

Python Version 2.7
Route Operating System: CISCO-IOS-XR
[ipv4_smiap.log](https://github.com/CiscoDevNet/ydk-gen/files/1368035/ipv4_smiap.log)

**Comment by abhikeshav** [comment]
Similar to #598 (same model, different container). See closing comments for #598
