### ISSUE TITLE
Track ydk-gen version and commit-id when generating ydk-py

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#6]
- profile file should have the version number for the ydk-py which is being generated
- ydk-py should document somewhere the link to the ydk-gen commit which was used to generate it

**Comment by psykokwak4** [comment]
Trying to use post-receive hook to print commit hash to a file and consume it when generating documentation

**Comment by abhikeshav** [comment]
Can you do something like 'git log -1' and get it at runtime? We don't want to be creating extra files which are going to be committed

**Comment by psykokwak4** [comment]
Ok, will try to get last pushed commit id and insert the link somewhere in documentation. And actually using git hook might not work since I need to add this hook to repository, and need to explicitly this hook to .git/hooks for every clone.

**Comment by psykokwak4** [comment]
checked in in 3f236757e3f1080a68af4bc62956bb6adf122e8b, printed a extra commit-id file as suggested

**Comment by psykokwak4** [comment]
Need to add a 'About YDK' page instead.

**Comment by abhikeshav** [comment]
<img width="726" alt="screen shot 2016-05-19 at 7 19 09 pm" src="https://cloud.githubusercontent.com/assets/17089095/15415313/b4a547a8-1df6-11e6-881f-6d95f1f8e0fd.png">
