### ISSUE TITLE
Python 3 suppport

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#60]

**Comment by abhikeshav** [comment]
This is blocked by ncclient not being available for python3

**Comment by 111pontes** [comment]
Not quite. Check out version 0.5.0 that has been made available for testing:
https://testpypi.python.org/pypi/ncclient/0.5.0
http://ncclient.org/

**Comment by abhikeshav** [comment]
Thanks, Santiago. I was able to pip install the test version of ncclient on python3. I am trying to run ydk-gen on python3. Among the changes we need to make to the code:
 - print function calls need parentheses around argument
 - need to start using string.format( {} ) style of string formatting 
 - some unicode-string conversions are needed

If we make all these changes + any more that show up, python3 can be supported for ydk-gen. Also, need to make similar changes to ydk-py (model APIs+runtime modules)

**Comment by 111pontes** [comment]
ydk-py-samples should be python3 ready

**Comment by 111pontes** [comment]
Already pushed to master.
