### ISSUE TITLE
Convert leafs to model type in YDK-Py

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#604]
Since YDK-Py 0.6.0, leafs have type [Yleaf](http://ydk.cisco.com/py/docs/api/types.html#ydk-types).  This type requires conversion (e.g. to int, to float, etc).  Using properties, a reference to a leaf could return data in the same type define in the data model.  That automatic conversion will improve usability.

**Comment by abhikeshav** [comment]
The sample [here](https://github.com/CiscoDevNet/ydk-py-samples/blob/master/samples/basic/crud/models/cisco-ios-xr/Cisco-IOS-XR-clns-isis-oper/nc-read-xr-clns-isis-oper-22-ydk.py#L72) is currently failing because all the leafs are `YLeaf` objects
