### ISSUE TITLE
Add support models with more than 256 type definitions

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#607]
YDK can't handle models with more than 256 type definitions.  The limitation comes from [libyang](https://github.com/CESNET/libyang).  We need to port the fix if available or implement it and contribute it upstream.

**Comment by einarnn** [comment]
Just FYI, this was a deliberate implementation decision by the libyang authors to conserve me,Orr for their primary use cases. Any fix we contribute will need to ensure we do not substantially increase memory or CPU usage. We hit this issue during yangcatalog work as well, and for now this is not a priority for the libyang primary authors.

**Comment by abhikeshav** [comment]
Fixed in latest code
