### ISSUE TITLE
Broken URL - Non-existing RPM for YDK

### ISSUE THREAD

**Issue by abhinava** [CiscoDevNet/ydk-gen#616]
## Expected Behavior
Publically available RPM for YDK - https://devhub.cisco.com/artifactory/rpm-ydk/0.6.2/libydk-0.6.2-1.x86_64.rpm

https://github.com/CiscoDevNet/ydk-gen#linux -- Install for CentOS

## Current Behavior
https://devhub.cisco.com/artifactory/rpm-ydk/0.6.2/libydk-0.6.2-1.x86_64.rpm is a broken link - The rpm-ydk/0.6.2/ directory doesn't exist on the server

## Steps to Reproduce
N/A

## Your Script
N/A

## Logs
(py2-ydk) [root@in-build-vd ydk-gen]# sudo yum install https://devhub.cisco.com/artifactory/rpm-ydk/0.6.2/libydk-0.6.2-1.x86_64.rpm
Loaded plugins: fastestmirror, langpacks
Cannot open: https://devhub.cisco.com/artifactory/rpm-ydk/0.6.2/libydk-0.6.2-1.x86_64.rpm. Skipping.
Error: Nothing to do

## System Information
[root@in-build-vd ~]# uname -a
Linux in-build-vd 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

[root@in-build-vd ~]# cat /etc/*-release
CentOS Linux release 7.4.1708 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core)
CentOS Linux release 7.4.1708 (Core)

**Comment by ylil93** [comment]
Hello,
The link is invalid currently because the RPM needs to be generated. Sorry for the inconvenience, but once they've been generated, we can fix this issue quickly. This should happen by tomorrow.

**Comment by abhinava** [comment]
Thanks! Will be very helpful.
I tried working around this by compiling YDK from source but I hit another issue - https://github.com/CiscoDevNet/ydk-gen/issues/615

**Comment by ylil93** [comment]
The core package is up now so feel free to use it now. Note that openconfig and cisco-ios-xe bundles are still in progress
