### ISSUE TITLE
Cisco_IOS_XR_ipv4_ma_oper: Segmentation fault occured while doing CRUD read operation

### ISSUE THREAD

**Issue by mjegathe** [CiscoDevNet/ydk-gen#621]
**Description**
While doing CRUD read operation for Cisco_IOS_XR_ipv4_ma_oper module got segmentation fault.

**Code Block**
   def get_ipv4_ma_oper_data(self):

        ipv4_io_data = Cisco_IOS_XR_ipv4_io_oper.Ipv4Network()

        self.device.read(ipv4_io_data)

**RPC Logs**
[Error for ipv4_io_oper_read.txt](https://github.com/CiscoDevNet/ydk-gen/files/1452636/Error.for.ipv4_io_oper_read.txt)

**System Info**

Tested in YDK-0.6.1. 
Platform: XRV9K

**Comment by mjegathe** [comment]
checked in YDK-0.6.2 and still segmentation fault occurred. Issue not resolved.

**Comment by abhikeshav** [comment]
Investigating. Could be related to this: https://github.com/CESNET/libyang/issues/388
