### ISSUE TITLE
clean up go code to adhere to style guidelines

### ISSUE THREAD

**Issue by ylil93** [CiscoDevNet/ydk-gen#634]
Go has well defined and strict style guidelines. It looks like much of our code that is written in Go defies these guidelines. Being that such code was written and committed before adding codacy support for Go, codacy doesn't detect violations until after someone modifies a file with such code in it, even if the new code doesn't affect or violate the guidelines.

We need to take a look at all files and make sure they adhere to the go style guidelines...

references:
https://www.codacy.com/app/ydk/ydk-gen/pullRequest?prid=1065839
https://golang.org/doc/effective_go.html#names
https://github.com/golang/go/wiki/CodeReviewComments

**Comment by abhikeshav** [comment]
Also, the ydk `godoc` documentation can be cleaned up.

To generate the go documents after setting `$GOPATH` and copying the ydk go packages, the below command will instantaneously generate the go docs for all the packages in `$GOSRC`

```
godoc -http=:6060 &
```

The ydk packages can then be browsed by going to the URL http://localhost:6060/pkg/

See [this link](http://blog.el-chavez.me/2013/08/29/golang-documenting-package-examples/) for more info.
