### ISSUE TITLE
ydk sanity yang files need to be consolidated in one location

### ISSUE THREAD

**Issue by ylil93** [CiscoDevNet/ydk-gen#636]
There are two locations that contain yang files:
ydk-gen/yang
ydk-gen/sdk/cpp/core/tests/models

Currently both locations are in use by different parts of the project, which is bad for many reasons.

To Do:
- consolidate models into ydk-gen/yang
- modify makefile in confd and other locations to reference ydk-gen/yang instead of ydk-gen/sdk/cpp/core/tests/models

A possible workaround solution could be to move all models into ydk-gen/yang and use symlinks in ydk-gen/sdk/cpp/core/tests/models

**Comment by abhikeshav** [comment]
Thanks @ylil93 for creating this issue! Made some minor edits for correct path

**Comment by ylil93** [comment]
Thanks for correcting the path @abhikeshav
