### ISSUE TITLE
Travis test sometime unexpectedly fails

### ISSUE THREAD

**Issue by ygorelik** [CiscoDevNet/ydk-gen#671]
## Current Behavior

Sometimes Travis tests unexpectedly fail in some of the OS images. 
After image retest the failed test passes.

## Expected Behavior

The Travis test should be more stable.

## Steps to Reproduce

The failure appears occasionally and seen only in part of the images

## Logs

Last failure appeared in go test on Ubuntu image, but passed on CentOS:

OpenDaylightProviderTestSuite: TestCreateODL ...
OpenDaylightProviderTestSuite: TestReadODL ...
RestconfProviderTestSuite: TestCreateDelRead ...
CodecTestSuite: TestJSONDecode ...
--- FAIL: TestJSONDecode (0.03s)
panic: YGOError: YCPPCodecError:Unknown element "bgp".. Path:  [recovered]
                panic: YGOError: YCPPCodecError:Unknown element "bgp".. Path: 
goroutine 72 [running]:
panic(0xcb4260, 0xc82000b130)
                /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
testing.tRunner.func1(0xc8200a4000)
                /usr/lib/go-1.6/src/testing/testing.go:467 +0x192
panic(0xcb4260, 0xc82000b130)
                /usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
github.com/CiscoDevNet/ydk-go/ydk/path.panicOnCStateError(0xc8202cd828)
                /ydk-gen/golang/src/github.com/CiscoDevNet/ydk-go/ydk/path/path.go:821 +0x109
github.com/CiscoDevNet/ydk-go/ydk/path.CodecServiceDecode(0xc8200579c8, 0xcb10e0, 0x7f9fb40270d0, 0x10aa160, 0x289, 0x1, 0x7f9fcaac9cd0, 0xc8200d5000, 0x0, 0x0)
                /ydk-gen/golang/src/github.com/CiscoDevNet/ydk-go/ydk/path/path.go:490 +0x7fe
github.com/CiscoDevNet/ydk-go/ydk/services.(*CodecService).Decode(0xc8200579d8, 0x7f9fcaac9ad8, 0xc820057998, 0x10aa160, 0x289, 0x0, 0x0)
                /ydk-gen/golang/src/github.com/CiscoDevNet/ydk-go/ydk/services/services.go:124 +0x1a0
_/ydk-gen/sdk/go/core/tests.(*CodecTestSuite).TestJSONDecode(0xc820057980)
                /ydk-gen/sdk/go/core/tests/service_codec_test.go:330 +0xc7
reflect.Value.call(0xcb8be0, 0xf2d308, 0x13, 0xf30eb8, 0x4, 0xc8202cdef8, 0x1, 0x1, 0x0, 0x0, ...)
                /usr/lib/go-1.6/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0xcb8be0, 0xf2d308, 0x13, 0xc8202cdef8, 0x1, 0x1, 0x0, 0x0, 0x0)
                /usr/lib/go-1.6/src/reflect/value.go:303 +0xb1
github.com/stretchr/testify/suite.Run.func2(0xc8200a4000)
                /ydk-gen/golang/src/github.com/stretchr/testify/suite/suite.go:102 +0x3c9
testing.tRunner(0xc8200a4000, 0xc820001c80)
                /usr/lib/go-1.6/src/testing/testing.go:473 +0x98
created by testing.RunTests
                /usr/lib/go-1.6/src/testing/testing.go:582 +0x892
exit status 2
FAIL       _/ydk-gen/sdk/go/core/tests     4.506s

**Comment by abhikeshav** [comment]
Not happening currently: https://travis-ci.org/CiscoDevNet/ydk-gen
