### ISSUE TITLE
Go YDK fails to build unique types for cascading typedef statements in Yang model

### ISSUE THREAD

**Issue by ygorelik** [CiscoDevNet/ydk-gen#675]
## Steps to Reproduce

Include the following statements (taken from NXOS) into Yang model and then build go bundle:

    typedef comp_InstType {
        type enumeration {
            enum unknown {
                value 0;   // Unknown
            }
            enum phys {
                value 1;     // Baremetal Host
            }
            enum virt {
                value 2;     // Virtual Machine
            }
            enum hv {
                value 3;   // Hypervisor Host
            }
        }
        default "unknown";
    }

    typedef comp_NicInstType {
        type comp_InstType;
    }

In this model the "comp_NicInstType" type "cascades" or "repeats" definition of "comp_InstType"

The Go API builder creates duplicate statements like this one, which causes compiler syntax error

// CompInstType
type CompInstType int
const (
    CompInstType_unknown CompInstType = 0
    CompInstType_phys CompInstType = 1
    CompInstType_virt CompInstType = 2
    CompInstType_hv CompInstType = 3
)

The type CompNicInstType does not appear in the Go code.

## Additional notes

The issue does not appear in C++ and Python bundle builders.

## Logs

TBD

## System Information
Ubuntu 14.1

**Comment by ylil93** [comment]
Also:
duplicate type and method definitions under cisco_ios_xe/native
589301:type Native_Interface_Vlan_CiscoIOSXEInterfacesSwitchportConf struct {
...
606925:type Native_Interface_Vlan_CiscoIOSXEInterfacesSwitchportConf struct {

**Comment by ylil93** [comment]
I've committed fixes that prevent the code from failing for now, but the issue with the api builder causes the documentation to be incorrect in both go and cpp.

**Comment by ygorelik** [comment]
The #891 was resolved in YDK-0.8.2. There are no more code duplication and XE bundle in Go is compiling fine. Hence closing the issue.
