### ISSUE TITLE
Some optional arguments in YDK-Py default to -1

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#682]
Some arguments in YDK-Py default to an unusual value of `-1` instead of `None`.  The change in defaults happened when YDK-Py 0.6.0 was introduced.  Some examples can be seen in the [NETCONF service](http://ydk.cisco.com/py/docs/api/services/netconf_service.html).  Other services or providers might have some instances too.

**Comment by abhikeshav** [comment]
Probably have to change the python wrapper code per [pybind11](https://pybind11.readthedocs.io/en/latest/advanced/functions.html#allow-prohibiting-none-arguments)
