### ISSUE TITLE
Netconf CRUD Read-Issue with ietf-interfaces augmentation 

### ISSUE THREAD

**Issue by asteinhagen** [CiscoDevNet/ydk-gen#693]
## Yang-models

Yang-models generated into .ydk/<IP-HOST-ADDRESS_PORT> directory.  
Introduced `&lt;` , `&gt;` , and `&amp;` 

Generated files:
[ydk-generated-yang-models.gz](https://github.com/CiscoDevNet/ydk-gen/files/1748532/ydk-generated-yang-models.gz)

Lines with above mentioned characters:
[yang-model-with-HTML-characters.gz](https://github.com/CiscoDevNet/ydk-gen/files/1748645/yang-model-with-HTML-characters.gz)

and corrected `<` , `>` , `&` characters.
[corrected-yang-models.gz](https://github.com/CiscoDevNet/ydk-gen/files/1748608/corrected-yang-models.gz)

Please see also Bug #692

## Expected Behavior

Return Interfaces config data via CRUD -Service.

## Current Behavior
```
a) Couldn't fetch schema node /ietf-interfaces:interfaces/interface[name='mgmt1/1/1']/dell-interface:mtu!
b) Couldn't fetch schema node /ietf-interfaces:interfaces/interface[name='ethernet1/1/1']/dell-interface:mtu!
```
## Pre-Analysis on Codec-Service
**_The codec-service on the extracted XML-code performs correctly._**
a) Script: [decode_get_interfaces.py.gz](https://github.com/CiscoDevNet/ydk-gen/files/1746195/decode_get_interfaces.py.gz)
b) Script: [decode_get_interfaces_1_1_1_mtu.py.gz](https://github.com/CiscoDevNet/ydk-gen/files/1746236/decode_get_interfaces_1_1_1_mtu.py.gz)

## Result of Codec-Service
a) [decode_get_interfaces_01.gz](https://github.com/CiscoDevNet/ydk-gen/files/1746212/decode_get_interfaces_01.gz)
b) [decode_get_interfaces_1_1_1_mtu_01.gz](https://github.com/CiscoDevNet/ydk-gen/files/1746239/decode_get_interfaces_1_1_1_mtu_01.gz)

## Steps to Reproduce
Use following script:

```
from ydk.providers import NetconfServiceProvider
from ydk.services import CRUDService
from ydk.services import NetconfService
from ydk.models.OS10E import ietf_interfaces
import pprint

import logging
log = logging.getLogger('ydk')
log.setLevel(logging.DEBUG)
handler = logging.StreamHandler()
log.addHandler(handler)

provider = NetconfServiceProvider(address = "10.11.56.165", port = 830,
                                  username = "admin", password = "admin", protocol = "ssh" )


crud = CRUDService()
intf_read = ietf_interfaces.Interfaces()

pprint.pprint(intf_read.__dict__)

status = crud.read(provider, intf_read)

print status


```

## Logs

a) [read_interfaces_01.gz](https://github.com/CiscoDevNet/ydk-gen/files/1746175/read_interfaces_01.gz)
b) [read_interfaces_interface_1_1_1_mtu_01.gz](https://github.com/CiscoDevNet/ydk-gen/files/1746252/read_interfaces_interface_1_1_1_mtu_01.gz)

## System Information

```
uname -a
Linux OS10EP-YDK070 3.16.43 #1 SMP Debian 3.16.43-2+deb8u5 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.10 (jessie)
Release:        8.10
Codename:       jessie

$ python -V
Python 2.7.13

$ pip freeze
ydk==0.7.0
```

**Comment by abhikeshav** [comment]
The `if-feature` issue should be fixed with #691. The fixed code will be part of `0.7.1` release of ydk

**Comment by asteinhagen** [comment]
Hello Abhi,
thank you for the quick reply,
where can I get the fixed code now to progress further?
Thank you
Achim

**Comment by abhikeshav** [comment]
The code is checked in to `ydk-gen` repository. Assuming you have all the dependencies installed, please follow the below steps in the same order to install the latest code:

```
# Generate & install libydk
$ ./generate.py --cpp --core
$ cd gen-api/cpp/ydk/build && make && sudo make install

# Generate & install ydk-py core
$ ./generate.py --python --core
$ pip install gen-api/python/ydk/dist/ydk*.tar.gz -U
```

**Comment by asteinhagen** [comment]
In a fresh virtual environment I started with the:
```
git clone https://github.com/CiscoDevNet/ydk-gen.git
```
I `diffed` the files where I could see on git-hubs history which ones were effected:
```
repository.cpp
data_node.cpp
netconf_session.cpp
schema_node.cpp
path_api.hpp
netconf_session.py
```
to make sure I have the latest files.

Then I followed exactly the steps you mentioned and came to the exact same outcome.

**Comment by abhikeshav** [comment]
Hi @asteinhagen , Is this issue still there with ydk `0.7.1`?

**Comment by abhikeshav** [comment]
Closing this issue as no response is received
