### ISSUE TITLE
Netconf CRUD Read-Issue with ietf-interfaces-state augmentation

### ISSUE THREAD

**Issue by asteinhagen** [CiscoDevNet/ydk-gen#694]
## Yang-models

Yang-model files generated into _.ydk/<IP-HOST-ADDRESS_PORT>_ directory.  
Introduced `&lt;` , `&gt;` , and `&amp;` 

Yang-model _filename_ and _lines_ with above mentioned introduced HTML-characters:

[HTML-characters_introduced.gz](https://github.com/CiscoDevNet/ydk-gen/files/1748826/HTML-characters_introduced.gz)

## Expected Behavior
Return Interfaces status data via Netconf CRUD-Service.

## Current Behavior
```
Couldn't fetch schema node /ietf-interfaces:interfaces-state/interface[name='ethernet1/1/1']/statistics/dell-interface:if-out-qlen!
```

## Another Encounter
_admin-status_ issues

[read_interfaces_state_admin-status.gz](https://github.com/CiscoDevNet/ydk-gen/files/1748969/read_interfaces_state_admin-status.gz)

_if-config_ issues

[read_interfaces_state_if-index.gz](https://github.com/CiscoDevNet/ydk-gen/files/1748971/read_interfaces_state_if-index.gz)

Temporary Solution:
In
```
ietf-interfaces.yang
```
comment the if-feature
as shown below:
```
      leaf admin-status {
        //if-feature if-mib;
        type enumeration {
```
```
      leaf if-index {
        //if-feature if-mib;
        type int32 {
```
## Yang-Models
[yang-model.tar.gz](https://github.com/CiscoDevNet/ydk-gen/files/1749136/yang-model.tar.gz)

## Pre-Analysis on Codec-Service
**_The codec-service on the extracted XML-code performs correctly._**
Remark: The XML portion is directly taken from the logging output of the script below.
[decode_get_interfaces_state.py.gz](https://github.com/CiscoDevNet/ydk-gen/files/1748875/decode_get_interfaces_state.py.gz)

## Result of Codec-Service
[decode_get_interfaces_state_01.gz](https://github.com/CiscoDevNet/ydk-gen/files/1748880/decode_get_interfaces_state_01.gz)

## Steps to Reproduce
Use following script:

```
from ydk.providers import NetconfServiceProvider
from ydk.services import CRUDService
from ydk.services import NetconfService
from ydk.models.OS10E import ietf_interfaces
import pprint

import logging
log = logging.getLogger('ydk')
log.setLevel(logging.DEBUG)
handler = logging.StreamHandler()
log.addHandler(handler)


provider = NetconfServiceProvider(address = "10.11.56.165", port = 830,
                                  username = "admin", password = "admin", protocol = "ssh" )
crud = CRUDService()
intf_state_read = ietf_interfaces.InterfacesState()
pprint.pprint(intf_state_read.__dict__)

status = crud.read(provider, intf_state_read)

print status

```

## Logs
[read_interfaces_state_06.gz](https://github.com/CiscoDevNet/ydk-gen/files/1749080/read_interfaces_state_06.gz)

## System Information

```
uname -a
Linux OS10EP-YDK070 3.16.43 #1 SMP Debian 3.16.43-2+deb8u5 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.10 (jessie)
Release:        8.10
Codename:       jessie

$ python -V
Python 2.7.13

$ pip freeze
ydk==0.7.0
```

**Comment by abhikeshav** [comment]
The `node not found` issue should be fixed with #691. The fixed code will be part of `0.7.1` release of ydk

**Comment by asteinhagen** [comment]
Hello Abhi,
where can I get the fixed code now to progress further?
Thank you
Achim

**Comment by abhikeshav** [comment]
The code is checked in to `ydk-gen` repository. Assuming you have all the dependencies installed, please follow the below steps in the same order to install the latest code:

```
# Generate & install libydk
$ ./generate.py --cpp --core
$ cd gen-api/cpp/ydk/build && make && sudo make install

# Generate & install ydk-py core
$ ./generate.py --python --core
$ pip install gen-api/python/ydk/dist/ydk*.tar.gz -U
```

**Comment by asteinhagen** [comment]
In a fresh virtual environment I started with the:
```
git clone https://github.com/CiscoDevNet/ydk-gen.git
```
I `diffed` the files where I could see on git-hubs history which ones were effected:
```
repository.cpp
data_node.cpp
netconf_session.cpp
schema_node.cpp
path_api.hpp
netconf_session.py
```
to make sure I have the latest files.

Then I followed exactly the steps you mentioned and came to the exact same outcome.

**Comment by abhikeshav** [comment]
Hi @asteinhagen , Is this issue still there with ydk `0.7.1`?

**Comment by abhikeshav** [comment]
Closing this issue as no response is received
