### ISSUE TITLE
Come up with solution for large model files in ydk-py

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#7]
Currently, git push to the github repository gives the below warning:

> remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
> remote: warning: See http://git.io/iEPt8g for more information.
> remote: warning: File ydk/models/infra/Cisco_IOS_XR_infra_policymgr_oper.py is 78.48 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
> remote: warning: File ydk/models/ipv4/Cisco_IOS_XR_ipv4_bgp_oper.py is 74.33 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB

Need to come up with a solution to fix these warnings

**Comment by 111pontes** [comment]
We may be able to streamline docstrings.  Also, following PEP8 may help.

**Comment by abhikeshav** [comment]
below approach can be used
```
git clone https://github.com/CiscoDevNet/ydk-gen.git
cd ydk-gen
pip install -r requirements
 
$ ./generate.py -h
usage: generate.py [-h] [--bundle BUNDLE]
                   [--adhoc-bundle-name ADHOC_BUNDLE_NAME]
                   [--adhoc-bundle ADHOC_BUNDLE [ADHOC_BUNDLE ...]] [--core]
                   [--output-directory OUTPUT_DIRECTORY] [-p] [-c] [-g] [-l]
                   [-v] [--generate-doc] [--generate-tests] [-o]
 
Generate YDK artefacts:
 
optional arguments:
...
-o, --one-class-per-module
                        Generate separate modules for each python class
                        corresponding to yang containers or lists.
 
./generate.py --bundle profiles/bundles/openconfig_0_1_5.json --python --one-class-per-module
 ```

Import:
```
from ydk.models.openconfig.openconfig_bgp import Bgp
 ```
changes to:
 ```
from ydk.models.openconfig.openconfig_bgp.bgp.bgp import Bgp
```
