### ISSUE TITLE
Publish ydk-py to PyPI (the Python Package Index)

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#70]

**Comment by einarnn** [comment]
How big is a typical ydk-py today? Or is the intent here to publish the base without any models?

**Comment by abhikeshav** [comment]
I think publishing the base YDK without any models is a key part of this.

Also, with the upcoming bundle user story, this will tie in to how we are going to package and publish bundles (all of which are going to be dependent on the base YDK)

**Comment by 111pontes** [comment]
Python package for YDK 0.4.0 is around 18MB.

**Comment by abhikeshav** [comment]
Fixed in 0.5.4
