### ISSUE TITLE
Code generation service

### ISSUE THREAD

**Issue by ghost** [CiscoDevNet/ydk-gen#71]
This enables users to handle below use cases as part of **YDK app maker (YAM)**
- Have netconf, restconf payload and want to migrate to YDK based app with minimal effort via tool.
- Looking for an educational channel on how to use YDK objects.
- Yang data model payload transcoding (convert XML to YDK to JSON to YDK python to .... or vice versa)

``` python
class CodeGenerationServiceProvider(object):
    """ Code generation provider"""
   def __init__(self, type):
        '''type is 'xml' or 'json' '''

class CodeGenerationService(object):
    """ Code generation service to generate code from XML/JSON payload """
   def __init__(self):
        pass
    def generate(self, provider, payload):
        '''This will return a python script snippet which can be used in a YDK app'''
```

It is preferable to continue using the existing service/provider abstraction

**Comment by abhikeshav** [comment]
There are some code changes made to support the YDK app maker. This is available on a separate branch. To try this, first, clone the ydk-py repo using the below command:
```
~/ > git clone https://github.com/CiscoDevNet/ydk-py.git -b yam
```
 
Then, follow the [steps here](https://github.com/CiscoDevNet/ydk-py#install-tips) to install ydk core and bundles.
 
To run the yam sample:
```
~/ > cd ydk-py/core/samples
~/ > ./yam_sample.py -v
```
