### ISSUE TITLE
How to implement support for multiple entities for services in Go

### ISSUE THREAD

**Issue by ygorelik** [CiscoDevNet/ydk-gen#743]
## Expected Behavior

Add support of multiple entities or no-entities in filter and results for CRUD, Netconf and Codec services in Go API.

## Current Behavior

Currently the CRUD, Netconf and Codec services accept and return single _Entity_ type structure.

## Issue description

Unlike C++ and Python languages the Golang does not have classes feature and does not allow overloaded functions. The type of parameters and results is strictly checked at compilation and cannot be changed in run-time. Therefore seamless introduction of multiple entities support in Go API is not possible.

We need to find a way to introduce this new feature, minimize changes to current Go API, make convenient for the user to use new API.

## Proposals

So far there are few proposals how the support for multiple entities or no-entities could be implemented in Go. All the proposals based on introduction of new type _EntityCollection_, which implements ordered collection of entities similar to implementation in Python. The new type will allow to have single and consistent function parameter and result, which can hold multiple Entity objects or have none.

**Proposal 1**
Change existing API for CRUD, Netconf and Codec services by replacing function parameters and returned type from _Entity_ to _EntityCollection_. Example:
_Current API_
  func (c *CrudService) Read( provider types.ServiceProvider, filter **types.Entity**) **types.Entity** { }
_New API_
  func (c *CrudService) Read( provider types.ServiceProvider, filter **EntityCollection**) **EntityCollection** { }

Arguments **For**: Clean user API.
Arguments **Against**: 1) Changes current API. 2) Big code refactoring for Services and Tests. 

**Proposal 2**
Add new functions by extending function name. Example:
  func (c *CrudService) **Read_**( provider types.ServiceProvider, filter EntityCollection) EntityCollection { }

Arguments **For**: Minimal code base and test impact.
Arguments **Against**: Expanded API can cause user confusion.

## Playground 
[Playground ](https://play.golang.org/p/yt6qF8RcWcg) for _EntityCollection_ type: 

## System Information
YDK0.7.1

**Comment by abhikeshav** [comment]
How about something like the below. Would this work to reduce the code churn?
```go
func (c *CrudService) Create( provider types.ServiceProvider, filter... Entity) bool { }
func (c *CrudService) Update( provider types.ServiceProvider, filter... Entity) bool { }
func (c *CrudService) Read( provider types.ServiceProvider, filter... Entity) EntityCollection { }
```

**Comment by ylil93** [comment]
Proposal for crud READ to support EntityCollection and remain backwards compatible:
Currently Read() takes two args: the provider and an object that implements the entity interface. If we have EntityCollection implement the entity interface (by defining GetEntityData() method) then we can satisfy this condition.

Caveats:
The Read() method will need to be modified to differentiate between and handle a regular Entity and the EntityCollection. This can be achieved with a type switch statement. https://tour.golang.org/methods/16

Additionally, there will need to be a different handling of the return type or the API needs to be modified to help the user differentiate between a regular Entity or an EntityCollection.
