### ISSUE TITLE
Corrupted path of a DataNode

### ISSUE THREAD

**Issue by ygorelik** [CiscoDevNet/ydk-gen#751]
## Current Behavior

The issue has been spotted in specific test case (see below). In the test the path of a DataNode appears corrupted (added some trash symbols at the end). 

_Current:_

**Printing DataNode: '/oc-pattern:oc-A[a='Hello']'**

_Expected:_

**Printing DataNode: '/oc-pattern:oc-A'**

The issue affects translation of DataNode to Entity, because path value is used for entity lookup.

## C++ Test
```cpp
TEST_CASE("TestXMLDecodeOCPattern")
{
    ydk::path::Repository repo{};

    ydk::path::NetconfSession session{repo, "127.0.0.1", "admin", "admin",  12022};
    ydk::path::RootSchemaNode& schema = session.get_root_schema();

    std::string xmlOCPatternPayload = R"(<oc-A xmlns="http://cisco.com/ns/yang/oc-pattern">
	<a>Hello</a>
</oc-A>)";
    ydk::path::Codec s{};
    auto dns = s.decode(schema, xmlOCPatternPayload, EncodingFormat::XML);
    for (auto dn : dns->get_children()) {
        print_data_node(dn);
    }
}
```
## System Information
ydk0.7.2

**Comment by abhikeshav** [comment]
This is not a bug. `oc-pattern` yang model has a list as top-level element. See the [yang model](https://github.com/CiscoDevNet/ydk-gen/blob/master/sdk/cpp/core/tests/models/oc-pattern%402015-11-17.yang#L42)

**Comment by ygorelik** [comment]
Appears not an issue in C++ code.

Fixed entity_utils.py to address algorithm, which used node path for building entity from data node. The script to test (part of unit test:

from ydk.entity_utils import _datanode_to_entity
xmlOCPatternPayload = ''<oc-A xmlns="http://cisco.com/ns/yang/oc-pattern"><a>Hello</a></oc-A>''

    def test_Codec_DecodeOCPattern(self):
        enable_logging(logging.DEBUG)
        schema = self.ncc.get_session().get_root_schema();
        codec = Codec()
        root_dn = codec.decode(schema, xmlOCPatternPayload, EncodingFormat.XML)
        for dn in root_dn.get_children():
            entity = _datanode_to_entity(dn)
            print_entity(entity, schema);
