### ISSUE TITLE
Add support for presence class in Go

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#763]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior

Encoding the YDK Go API for below YANG model should produce below output:
```yang
    container outer {
        container inner {
            presence true;
        }
    }
```

```xml
<outer>
  <inner/>
<outer>
```

## Current Behavior

presence container is not supported in Go

**Comment by ylil93** [comment]
the fix can be something like this
https://play.golang.org/

**Comment by ylil93** [comment]
fixed
