### ISSUE TITLE
YDK hangs when called from within a long running python process

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#770]
## Expected Behavior
YDK should work when called from a long-running python process

## Current Behavior
With a YDK service+provider created inside a [NATS server](https://github.com/nats-io/gnatsd) instance, YDK-Py hangs inside the provider ([see for example](https://github.com/CiscoDevNet/ydk-gen/blob/4824bcf9132824156e70a629a0d91d7be4e7ecf2/sdk/python/core/ydk/entity_utils/entity_utils.py#L74)) when calling C++ function wrapper like [this one](https://github.com/CiscoDevNet/ydk-gen/blob/4824bcf9132824156e70a629a0d91d7be4e7ecf2/sdk/python/core/python.cpp#L1060).

Tried the below approaches, but it does not help:

-  https://docs.python.org/2/library/multiprocessing.html#using-a-pool-of-workers
- https://github.com/CiscoDevNet/ydk-gen/issues/434

The issue could likely related to pybind11. See for reference: 
 - https://pybind11.readthedocs.io/en/latest/advanced/misc.html?#global-interpreter-lock-gil

**Comment by ygorelik** [comment]
I tried reproduce the issue in REST server with various YDK services. In all the attempts the YDK worked as expected. The issue most likely appears in NAT server environment, which we could not build on our side.

**Comment by ygorelik** [comment]
The ROBOT team reported that "The issue has been resolved, it was a bug in the NATS client library that we were using for starting the long running server. The forever running ioloop shouldn’t have been running in a thread.
https://github3.cisco.com/ROBOT/infra-messaging-nats/pull/15"
