### ISSUE TITLE
YError exception not raised as expected

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#773]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
YDK should generate `YError` exceptions.

## Current Behavior
YDK generates `RuntimeError` exception when an invalid namespace is sent in a NETCONF subtree filter.

## Steps to Reproduce
Using Path API, send a NETCONF `get` RPC with filter:
```xml
<netconf-state xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring2">
  <schemas/>
</netconf-state>
```

## Logs
```
RuntimeError: YServiceProviderError: <?xml version="1.0"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>unknown-namespace</error-tag>
    <error-severity>error</error-severity>
    <error-info>
      <bad-element>netconf-state</bad-element>
      <bad-namespace>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring2</bad-namespace>
    </error-info>
  </rpc-error>
</rpc-reply>
```

## System Information
```
$ python --version
Python 3.5.2
$ pip list | grep ydk
ydk                     0.7.1
ydk-models-cisco-ios-xr 6.3.2
ydk-models-ietf         0.1.5
$
```

**Comment by ygorelik** [comment]
Could not reproduce after #774 got fixed.
