### ISSUE TITLE
cgo compile error

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#781]
Seeing error:
```
invalid flag in #cgo LDFLAGS:  ...
```

Could be related to: https://github.com/golang/go/issues/23749

Need to investigate different compiler options to use to make it work on `Go 1.10`

**Comment by abhikeshav** [comment]
# Workaround

 * Use a version of Go that doesn't have this problem

**Comment by 111pontes** [comment]
Go 1.10 is the default version in many systems.  This issue should be address soon as ydk-go would be broken out of the box for many users.

**Comment by abhikeshav** [comment]
Need to ensure the default Go version for platform (ubuntu/centos) is supported. If default version for platform is not supported, this should be documented. Need to check `go version`.

**Comment by ygorelik** [comment]
The code specifies additional CGO flags to enable coverage tests. In order to ignore the flags the following environment variable should be set before compiling the Go code:
```
export CGO_ENABLED=1
export CGO_LDFLAGS_ALLOW="-fprofile-arcs|-ftest-coverage|--coverage"
```
Added above setting to Travis tests.
