### ISSUE TITLE
bug in get_children()

### ISSUE THREAD

**Issue by ylil93** [CiscoDevNet/ydk-gen#795]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
get_children() should return all the child classes of the class on which the method is called. 

In ydk.models.ietf.ietf_netconf_monitoring.NetconfState.Schemas, we should get back a ChildrenMap populated with ydk.models.ietf.ietf_netconf_monitoring.Schema, but this is not the case.
For the time being, I am able to work around this bug by directly calling on the _child_classes member.
```
# clazz being an instance of ydk.models.ietf.ietf_netconf_monitoring.NetconfState.Schemas
(Pdb) clazz._child_classes
OrderedDict([('schema', ('schema', <class 'ydk.models.ietf.ietf_netconf_monitoring.Schema'>))])
(Pdb) len(clazz._child_classes)
1
```

## Current Behavior
```
# clazz being an instance of ydk.models.ietf.ietf_netconf_monitoring.NetconfState.Schemas
(Pdb) clazz.get_children()
ChildrenMap{}
(Pdb) len(clazz.get_children())
0

```

## Steps to Reproduce / Your Script

```
from ydk.models.ietf import ietf_netconf_monitoring
clazz = ietf_netconf_monitoring.NetconfState().Schemas()
print clazz.get_children()
print len(clazz.get_children())
print clazz._child_classes
print len(clazz._child_classes)
```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

## System Information

python 2.7

**Comment by abhikeshav** [comment]
This is as expected. `get_children()` only returns children if the children have any data. For example, below shows more than 1 child:
```py
from ydk.models.ietf import ietf_netconf_monitoring
clazz = ietf_netconf_monitoring.NetconfState().Schemas()
s=clazz.Schema()
s.identifier='ietf-netconf'
s.revision = '2017'
s.format=ietf_netconf_monitoring.Yang()
clazz.schema.append(s)
print (clazz.get_children())
print (len(clazz.get_children()))
print (clazz._child_classes)
print (len(clazz._child_classes))

```
