### ISSUE TITLE
SDK version shouldn't be hard coded

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#8]
The version of the generated SDK shouldn't be hard coded in the SDK files.  The generation profile already specifies the version number. That version should be added to the SDK package during generation.

**Comment by einarnn** [comment]
Can you point to an example of this?

**Comment by 111pontes** [comment]
See https://github.com/CiscoDevNet/ydk-gen/blob/master/sdk/python/setup.py  Shouldn't version be an attribute of the profile that is reflected automatically in the generated package?

**Comment by einarnn** [comment]
Yes. That should be a template that is processed at build time and substituted with the correct version number coming, as you say, from the profile file.

Cheers,

Einar

**Comment by 111pontes** [comment]
Version is already captured in the profile. What is missing is propagating that value to the package during generation.  That's what this issue was created for. Hope that clarifies.

**Comment by psykokwak4** [comment]
Merged after commit bc80f443707b050b87f460e46ea4d8630a741748
