### ISSUE TITLE
Does the ydk-gen provide functions to implement a NETCONF server?

### ISSUE THREAD

**Issue by vhuertas** [CiscoDevNet/ydk-gen#804]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Current Behavior
Hi all,
I would like to implement in c++ a NETCONF server on a custom device using the ydk-gen. The yang models parsing capabilities of ydk-gen generates all the c++ classes, which is very useful. 

however I would like to know if the core API provides some functions to implement the server side of the NETCONF and not only the client. If not, Is it contemplated as a future implementation?

Regards,

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

**Comment by abhikeshav** [comment]
YDK is meant to be a client-side SDK. We do not plan to extend it to server side
