### ISSUE TITLE
Fix YDK cpp bundle generation to escape standard names

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#810]
With the current ydk-gen, C++ XE, XR bundles are produced which cannot be compiled as many standard C++ keywords are not escaped when these are present in the yang models.

After generating the models, the below edits had to be done in order to get the generated XR, XE bundles to compile:

https://github.com/CiscoDevNet/ydk-cpp/commit/259103eaf16b3efa035e7791b2ed1e281197c08d

These need to be generated correctly by ydkgen

**Comment by abhikeshav** [comment]
[libssh-0.7.5.zip](https://github.com/CiscoDevNet/ydk-gen/files/2462563/libssh-0.7.5.zip)

**Comment by ygorelik** [comment]
Resolved to YDK 0.7.3 and 0.8.0.
