### ISSUE TITLE
add default value attribute for each leaf object

### ISSUE THREAD

**Issue by xulleon** [CiscoDevNet/ydk-gen#813]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

In a container, if it has a member,
## Expected Behavior
expect._default_value to provide the leaf default value.. similar to the _range attribute for a leaf object.

## Current Behavior
current leaf object has no default value

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

**Comment by abhikeshav** [comment]
Fixed in bfb7b603bdd769672c84a6f43f4230c46eb98f34
