### ISSUE TITLE
deletion of an object with children configured will be rejected

### ISSUE THREAD

**Issue by xulleon** [CiscoDevNet/ydk-gen#814]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
regardless if a child is configured under an object, CRUD service should be able to delete the object

## Current Behavior
deletion of an object with children configured will be rejected

*** ydk.errors.YPYServiceProviderError: Server rejected request.
        error-type: application
        error-tag: operation-failed
        error-severity: error
        error-message: The requested operation failed.

## Steps to Reproduce
take Openconfig bgp for an example,
1) if a protocol is configured with bgp, may also have a neighbor configured.
2) delete the protocol will be rejected

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

**Comment by abhikeshav** [comment]
I don't think YDK should handle this. The below script can be used as example of how to delete using object with children.

```py
from ydk.models.openconfig import openconfig_network_instance
from ydk.providers import NetconfServiceProvider      
from ydk.services import CRUDService                                                                                                                                                                                                

crud = CRUDService()
ncc = NetconfServiceProvider(address='<host>' , username='<user>', password='<pass>')

# Read top object
nis = openconfig_network_instance.NetworkInstances()
network_instances=crud.read(ncc,nis,only_config=True)

# Create object to be deleted
bgp_obj=network_instances.network_instance[0].protocols.protocol[2].bgp.__class__()
# Set parent
bgp_obj.parent = q.network_instance[0].protocols.protocol[2]
crud.delete(ncc,bgp_obj)

```
