### ISSUE TITLE
adding new operations, merge, replace, remove

### ISSUE THREAD

**Issue by xulleon** [CiscoDevNet/ydk-gen#816]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
for a specific ydk object, MERGE, REPLACE, REMOVE are missed.
there were bugs found when perform MERGE, REPLACE and REMOVE

## Current Behavior
currently only DELETE operation is available, 

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

**Comment by abhikeshav** [comment]
fixed in 46532a534c3ef4409f51d4a4e711c0ffde73a38e
