### ISSUE TITLE
ydk core generation failed due to a typo

### ISSUE THREAD

**Issue by xulleon** [CiscoDevNet/ydk-gen#818]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
ydk core can be generated successfully

## Current Behavior
failed to generate ydk core due to 
def get_default_value_object(ptype, property_type, clazz_name, default_value, identity_subclasses):
    default_value_object = ''
    if ptype == 'Empty':
        default_value_object = "'Empty()'"
    elif ptype == 'str':
        default_value_object = '"\'%s\'"' % default_value
    or ptype == 'int': <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<, I guess that you mean elif instead of or
        default_value_object = '"%s"' % default_value
    elif ptype == 'Decimal64':
        default_value_object = '\'Decimal64("%s")\'' % default_value
    elif ptype == 'bool':

at File "/auto/leoxu-patton1/pyats/ydk-gen/ydkgen/printer/meta_data_util.py", line 655

after change "or" to "elif", problem was resolved.

## Steps to Reproduce
./generate.py --core --python

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```
pyats] sjc-ads-3460:670> ./generate.py --core --python
Traceback (most recent call last):
  File "./generate.py", line 33, in <module>
    from ydkgen import YdkGenerator
  File "/auto/leoxu-patton1/pyats/ydk-gen/ydkgen/__init__.py", line 35, in <module>
    from ydkgen.printer import printer_factory
  File "/auto/leoxu-patton1/pyats/ydk-gen/ydkgen/printer/__init__.py", line 27, in <module>
    from .python.class_docstring_printer import ClassDocstringPrinter
  File "/auto/leoxu-patton1/pyats/ydk-gen/ydkgen/printer/python/class_docstring_printer.py", line 23, in <module>
    from ydkgen.printer.meta_data_util import get_class_docstring
  File "/auto/leoxu-patton1/pyats/ydk-gen/ydkgen/printer/meta_data_util.py", line 655
    or ptype == 'int':
     ^
SyntaxError: invalid syntax
```

**Comment by abhikeshav** [comment]
Fixed in 0c6e695fca9de8084e20b8e1c527310b1603b696
