### ISSUE TITLE
documentation specified ydk-cisco-ios-xr does not exist

### ISSUE THREAD

**Issue by echen102** [CiscoDevNet/ydk-gen#838]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Current Behavior
Documentation for YDK asks users to install the following: 
pip install ydk-cisco-ios-xr

This package does not exist, and should be replaced with ydk-models-cisco-ios-xr

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

**Comment by ygorelik** [comment]
Resolved in YDK-0.8.0
