### ISSUE TITLE
NETCONF Service Provider TCP transport not documented properly

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#850]
Current documentation for NETCONF Service Provider is unclear regarding support for insecure transport (TCP).  Documentation for the `protocol` argument should clearly state that secure (SSH) and insecure (TCP) connections are supported.

![image](https://user-images.githubusercontent.com/16885441/50865749-df405e00-135b-11e9-96eb-87045e70ed30.png)

**Comment by ygorelik** [comment]
Fixed in 0.8.1.
