### ISSUE TITLE
YDK return value of YANG action missing some attributes

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#871]
Currently, the result of a running a YANG action is returned as a datanode [here](https://github.com/CiscoDevNet/ydk-gen/blob/2e22b29a2fdbf9935b929f0501a5f9ee223aaebd/sdk/cpp/core/src/netconf_session.cpp#L320). However, when the return value of this function is encoded using YDK path `Codec`, it seems to be missing some parts of the data.

**Comment by NitishV** [comment]
Please find attached a test script and log used to re-produce this issue.

[nso_action_rpc_test_code.txt](https://github.com/CiscoDevNet/ydk-gen/files/2985717/nso_action_rpc_test_code.txt)
[ydk_bug_871.log](https://github.com/CiscoDevNet/ydk-gen/files/2985718/ydk_bug_871.log)

**Comment by ygorelik** [comment]
The tailf Yang models use extensions defined in _tailf-commmon.yang_, including definition of _sync-from_ node. This feature is not supported by YDK, which causes the described symptoms. All the Yang model extensions are simply dropped in YDK.

In order to provide some ways to analyze RPC data received from device, it was developed new API function, which returns data as a string (str):
```
    str NetconfSession.execute_netconf_operation( Rpc )
```
Here is the script with this new feature: 
```
from ydk.providers import NetconfServiceProvider
from ydk.path import Repository
from ydk.services import Datastore
from ydk.path import Codec
from ydk.types import EncodingFormat
import logging
logger = logging.getLogger('ydk')

router_ip = '192.168.123.11'

provider = NetconfServiceProvider(repo=Repository('/opt/robot/data/cache'), address='192.168.123.111', username='nso', password='cisco123', port=2022)

data = '''<devices xmlns="http://tail-f.com/ns/ncs"><device><name>%s</name><sync-from/></device></devices>'''%router_ip

rpc = provider.get_session().get_root_schema().create_rpc("tailf-actions:action")
rpc.get_input_node().create_datanode("data", data)

result = provider.get_session().execute_netconf_operation(rpc)
print(result)
```
The script produces this result:
```
root@robot-nca-66dfd4ff7f-88dm7:/var/log/robot# python test_871.py
<data>
    <devices xmlns="http://tail-f.com/ns/ncs">
      <device>
        <name>192.168.123.11</name>
        <sync-from>
          <result>false</result>
        </sync-from>
      </device>
    </devices>
  </data>
```
