### ISSUE TITLE
top level container missed mtype in YDK5.5

### ISSUE THREAD

**Issue by xulleon** [CiscoDevNet/ydk-gen#887]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

For a module, there are 4 top nodes, two of them are list another two are containers. mtype can be used to determine if any of the node is a list. However this attribute is missing

## Expected Behavior
this is a non-top-node, by dir mtype can be seen

(Pdb) dir(meta_g1.meta_info_class_members[0])
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_clazz_name', '_default_value', '_doc', '_is_config', '_is_key', '_max_elements', '_members', '_min_elements', '_module_name', '_mtype', '_name', '_pattern', '_pmodule_name', '_presentation_name', '_ptype', '_range', '_ytype', 'clazz_name', 'default_value', 'is_key', 'max_elements', 'members', 'min_elements', 'module_name', **'mtype**', 'name', 'pmodule_name', 'presentation_name', 'ptype', 'union_list', 'ytype']

## Current Behavior
if it is top obj, g1 is a top obj. mtype is missing

(Pdb) dir(g1)
['AddressFamily', 'Mode', 'RemoteRouteFiltering', 'Vpn', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_common_path', '_has_data', '_meta_info', '_prefix', '_revision', 'address_family', 'description', 'is_config', 'mode', 'remote_route_filtering', 'vpn', 'vrf_name', 'ylist_key_names']

## Steps to Reproduce
create a top obj and dir the obj

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

**Comment by ygorelik** [comment]
The issue has been resolved in YDK-0.5.5.post2 with this [commit](https://github.com/CiscoDevNet/ydk-gen/commit/dbe2dd48a6fd1bd2bd64179a750cb72f3303a36d).
