### ISSUE TITLE
add _is_present attribute in present container

### ISSUE THREAD

**Issue by xulleon** [CiscoDevNet/ydk-gen#896]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
when a container is a presence container, the container should have an attribute called _is_present to let user know that this container is a special one and a kind of presence container

## Current Behavior
the attribute of _is_present does not exist

## Steps to Reproduce
>>> from ydk.models.cisco_iosxr_705 import Cisco_ios_xr_interface_cfg
>>> multi = Cisco_ios_xr_interface_cfg.Interfaces.Interface.Mpls.LabelSecurity.MultiLabelPacket()
>>> meta = multi._meta_info()
>>> from pprint import pprint;pprint(vars(meta.meta_info_class_members[0]))
{'_clazz_name': 'Interfaces.Interface.Mpls.LabelSecurity.MultiLabelPacket.Drop',
 '_default_value': None,
 '_doc': '                Drop packets with multiple labels on the stack\n'
         '                ',
 '_is_config': True,
 '_is_key': False,
 '_max_elements': None,
 '_members': [],
 '_min_elements': None,
 '_module_name': 'Cisco-ios-xr-if-mpls-cfg',
 '_mtype': 1,
 '_name': 'drop',
 '_pattern': [],
 '_pmodule_name': 'ydk.models.cisco_iosxr_705.Cisco_ios_xr_interface_cfg',
 '_presentation_name': 'drop',
 '_ptype': 'Drop',
 '_range': [],
 '_ytype': ''}

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

**Comment by abhikeshav** [comment]
Fixed with 9b6a5dab004ac1bd4b328450380956cc1c162420
