### ISSUE TITLE
Add function to return Enum object from type and value

### ISSUE THREAD

**Issue by xulleon** [CiscoDevNet/ydk-gen#926]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
inputs:
- Enum type in string format: i.e. 'TypeEnum'
- Enum value (optional): in string or int

return: if enum value is not given, the function will return the Enum object
             if enum value is given, the function will return the Enum object with the value assigned.

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

**Comment by ygorelik** [comment]
Implemented in releases 0.5.5.post2 and 0.8.4
