### ISSUE TITLE
navigate a xpath is not covered if the middle path is a list and has more than 2 items.

### ISSUE THREAD

**Issue by xulleon** [CiscoDevNet/ydk-gen#928]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
In the file below, it can only support the following

/path1/path2/...../pathn-1[more than two items]/pathn

but not work for the following

/path1/path2/...../pathm-1[more than two items]/pathm/........../pathn-1/pathn

ydk/providers/_provider_plugin.py
        for yang_node_name in yang_nodes:

            found = False
            for member in current._meta_info().meta_info_class_members:
                if member.name == yang_node_name:
                    found = True
                    current = getattr(current, member.presentation_name)
                    if current is None:
                        return None
                    if isinstance(current, YList):
                        if len(current) == 0:
                            return None
                        if len(current) >= 2:
                            return _get_child_values_if_possible(yang_node_name, yang_nodes, current)
                        if len(current) == 1:
                            current = current[0]
                    break

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

**Comment by ygorelik** [comment]
Resolved to 0.5.5.post2 and 0.8.4.
