### ISSUE TITLE
NETCONF service doesn't implement get-schema operation

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#96]
Support for get-schema operation is missing

**Comment by einarnn** [comment]
Arguably it doesn't need it, does it? It seems naively that if you're using the ydk, then you're using the API generated from the models. Having said that, I don't see the harm in making available a pass-thru call to the underlying ncclient module. Or maybe just allow that to be retrieved more easily?

**Comment by 111pontes** [comment]
Agree that, in theory, getting YANG files wouldn't be needed.  However, there are use cases where this could be useful (e.g. to generate API on the fly).  I don't see a down side to implement it and it should be simple to add it.

**Comment by 111pontes** [comment]
IETF bundle in YDK 0.5.1 includes ietf-netconf-monitoring model and the RPC executor service.  These two expose the get-schema RPC to users.
