### ISSUE TITLE
Shared library issue while installing ydk!

### ISSUE THREAD

**Issue by sindhujit** [CiscoDevNet/ydk-gen#981]
Hi,
I have included the python installation in LD_LIBRARY_PATH, but while installing ydk through "pip install ydk", I am getting the following error:

```
/tmp/pip-install-5vc0wm56/ydk/python.cpp:541:39: warning: unused parameter â€˜leftâ€™ [-Wunused-parameter]
.def("__eq__", [](ydk::Empty& left, ydk::Empty& right)
^
/tmp/pip-install-5vc0wm56/ydk/python.cpp:541:57: warning: unused parameter â€˜rightâ€™ [-Wunused-parameter]
.def("__eq__", [](ydk::Empty& left, ydk::Empty& right)
^
/tmp/pip-install-5vc0wm56/ydk/python.cpp:545:39: warning: unused parameter â€˜leftâ€™ [-Wunused-parameter]
.def("__ne__", [](ydk::Empty& left, ydk::Empty& right)
^
/tmp/pip-install-5vc0wm56/ydk/python.cpp:545:57: warning: unused parameter â€˜rightâ€™ [-Wunused-parameter]
.def("__ne__", [](ydk::Empty& left, ydk::Empty& right)
^
[100%] Linking CXX shared module ../lib.linux-x86_64-3.6/ydk_.so
/opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.3.1/ld: /usr/local/lib/libpython3.6m.a(abstract.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a: error adding symbols: Bad value
```

I am not sure why while installing ydk through pip install ydk, it tries to use my global libpython install 
/usr/local/lib/libpython3.6

`/opt/rh/devtoolset-4/root/usr/libexec/gcc/x86_64-redhat-linux/5.3.1/ld: /usr/local/lib/libpython3.6m.a(abstract.o): relocation R_X86_64_32 against .rodata.str1.8' can not be used when making a shared object; recompile with -fPIC`

My pip and python install are under a virtualenv :
```
(netadc_sgang31) [root@hqidlavxwa02 netadc3]# which pip
/root/.venvs3/netadc_sgang31/bin/pip
```
All other python packages installed fine for the past year or so since our application was launched. Please help!

**Comment by ygorelik** [comment]
This is not YDK but rather user setup environment issue. Please see details of this discussion [here](https://community.cisco.com/t5/yang-development-kit-ydk/shared-libraries-error-while-installing-ydk/m-p/4001552).
