### ISSUE TITLE
RuntimeError: YIllegalStateError: Could not create repository in: /root/.ydk/x.x.x.x

### ISSUE THREAD

**Issue by sindhujit** [CiscoDevNet/ydk-gen#982]
Getting the error

`RuntimeError: YIllegalStateError: Could not create repository in: /root/.ydk/x.x.x.x`
when trying to use NetconfServiceProvider on a cisco nxos switch.

**Comment by ygorelik** [comment]
Not YDK issue, but rather user environment issue. See details of the discussion [here](https://community.cisco.com/t5/yang-development-kit-ydk/shared-libraries-error-while-installing-ydk/m-p/4001552).
