### ISSUE TITLE
YDK Core dumped on CRUD operation to delete class-map and associated policy-map-rule

### ISSUE THREAD

**Issue by vsoaresf** [CiscoDevNet/ydk-gen#985]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
The NETCONF server should be capable through the dependencies to decide the order of the operations. First it should remove the  policy-map-rule and after remove the class-map.

## Current Behavior

It tries to remove first the class-map and then it fails due to an existing association of that class-map to a policy-map-rule. And as a result of the issue Core dump on failed XML RPC #984 it crashes with a core dump

## Steps to Reproduce

Using the Cisco_IOS_XR_infra_policymgr_cfg try to delete an existent class-map and related policy-map-rule in a given policy-map

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```
[ydk.log](https://github.com/CiscoDevNet/ydk-gen/files/4064900/ydk.log)

```

## System Information

python –version -> Python 3.6.8
 
pkg-resources==0.0.0
pybind11==2.4.3
ydk==0.8.4
ydk-models-cisco-ios-xr==6.6.3
ydk-models-ietf==0.1.5.post2

Distributor ID:   Ubuntu
Release:              18.04
Codename:        bionic

**Comment by ygorelik** [comment]
That issue must be resolved from application side. There is no need to delete child _policy-map-rule_ container when you are deleting the parent container _class-map_ in the same transaction. Hence closing the issue.
