### ISSUE TITLE
lyd_print_mem with LYD_JSON in libyang bundled with YDK not working

### ISSUE THREAD

**Issue by hotlib** [CiscoDevNet/ydk-gen#986]
When I install ydk-cpp and try to access and use libyang which is included in ydk-cpp I am unable to generate a valid JSON via the [lyd_print_mem](https://netopeer.liberouter.org/doc/libyang/master/group__datatree.html#ga5dee9dd41c57edc1fc2185f6a2c233a3) call. 

## Expected Behavior
I'd expect the call lyd_print_mem(&buff, some_node, LYD_JSON, 0) to produce a valid JSON representing the actual data.

## Current Behavior
I either get an invalid JSON like {, ...} (starting with a comma) or an empty json {} although the data is there. Example of an malformed JSON:

`{,"openconfig-interfaces:state":{"admin-status":"UP","counters":{"in-broadcast-pkts":"2767641","in-discards":"0","in-errors":"0","in-multicast-pkts":"5769311","in-octets":"427066814515","in-unicast-pkts":"293117","out-broadcast-pkts":"7628","out-discards":"0","out-errors":"0","out-multicast-pkts":"325039","out-octets":"72669652","out-unicast-pkts":"125182"},"enabled":true,"mtu":1518,"name":"0/3","oper-status":"DOWN","type":"iana-if-type:ethernetCsmacd"}}`

## Steps to Reproduce

Basically try to print any non-trivial tree and you get a malformed JSON. Example for code that produces the given behavior:
[test.cpp](https://github.com/hotlib/random/blob/master/test.cpp) Full working example: [ydkbug.zip](https://github.com/hotlib/random/blob/master/ydkbug.zip) (Note: you have to have ydk-cpp installed for the example to work)

## Further information

The same lyd_print_mem works fine with the current [libyang master](https://github.com/CESNET/libyang), the problem might be in the [fork](https://github.com/ygorelik/libyang) and the custom changes in the area of printing JSONs (printer_json.c?). Generating XML via lyd_print_mem seems to work correctly.

## System Information
machine: Linux xxx 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 

ydk-cpp is the newest from master 

The libyang used inside ydk-cpp is [https://github.com/ygorelik/libyang/archive/master.zip](https://github.com/ygorelik/libyang/archive/master.zip)

**Comment by ygorelik** [comment]
Resolved with [this](https://github.com/ygorelik/libyang/commit/6f65ae63a554fdb58b1ae3605c67c9eaf4a5ed19) commit to https://github.com/ygorelik/libyang.
After the fix the test program outputs (with pretty print):
```
{
  "openconfig-interfaces:state": {
    "admin-status": "UP",
    "counters": {
      "in-broadcast-pkts": "2767641",
      "in-discards": "0",
      "in-errors": "0",
      "in-multicast-pkts": "5769311",
      "in-octets": "427066814515",
      "in-unicast-pkts": "293117",
      "out-broadcast-pkts": "7628",
      "out-discards": "0",
      "out-errors": "0",
      "out-multicast-pkts": "325039",
      "out-octets": "72669652",
      "out-unicast-pkts": "125182"
    },
    "enabled": true,
    "mtu": 1518,
    "name": "0/3",
    "oper-status": "DOWN",
    "type": "iana-if-type:ethernetCsmacd"
  }
}
```
The JSON output validate with online tool.
